10.9-libcxx/stable/main/finkinfo/languages/gcc7.info

Tested on 10.13 with 'fink -m' for against both Xcode 6.2 and 6.3 beta.

Update to gcc 7.3.0

---

10.9-libcxx/stable/main/finkinfo/sci/dcw-gmt.info

This is to update the Fink package to upstream's version 1.1.3

Updated dcw-gmt from 1.1.2-1 to 1.1.3-1

---

10.9-libcxx/stable/main/finkinfo/sci/cdo.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-cxx4.info

I'd like to propose this addition to Fink: cdo-openmp. This provides parallelization through openmp to CDO. I got some requests from Fink users for this.
cdo-openmp uses gcc7-compiler. To avoid that all cdo users need to install gcc7-compiler, I made cdo-openmp as a conflicts/replaces to cdo (and vice versa).
I think it is easy to maintain them in parellel.

Add cdo-openmp and update netcdf-cxx4

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/python-ldap-py.info

Remove a bunch of seemingly-unused dependencies (instrumented the
build with f-p-p to help diagnose). Possibly these are long-obsolete
inherited build-depends of the only directly used library or lingering
from older upstream version that used these directly as well.

python-ldap-py dependency cleanup

---

10.9-libcxx/stable/main/finkinfo/devel/cmake.info

The package autodetects libidn2 and does not detect libidn; if it does
not detect libidn2, it builds without support for...something. Deps
for libidn suggest intent to support, so switch deps to libidn2.

cmake: fix libidn detection/linking

---

10.9-libcxx/stable/main/finkinfo/net/znc.info

Previous FTBFS on 10.13; easiest fix was to ugprade to the latest
upstream. That also enabled switching to openssl110

znc: new version

---

10.9-libcxx/stable/main/finkinfo/sci/gmt5.info

This is similar to what Daniel did in some other packages.
I did not update the revision number since this does not affect the package content for those who use /sw.

gmt5: virtualize explicit /sw in cmake sources by %p

---

10.9-libcxx/stable/main/finkinfo/utils/diffutils.info
10.9-libcxx/stable/main/finkinfo/utils/diffutils.patch

Prevents runtime (and self-test) segfault. Also remove ConfigureParams path settings that are already the default
in ./configure

diffutils: standard 10.13 fix for gnulib vasnprintf

---

10.9-libcxx/stable/main/finkinfo/text/miktex-tools.info

libgraphite dependency sanity; openssl110 upgrade.
@nieder, I'm just doing this mechanically ("it builds and passes tests"). Is there a reason we might want on-board libgraphite and/or remain with openssl100?

Miktex-tools dependencies

---

10.9-libcxx/stable/main/finkinfo/sci/staden.info
10.9-libcxx/stable/main/finkinfo/sci/staden.patch

The package hardcoded the path to the specific version of tklib, whereas other tcl/tk wildcarded it. Wildcard it so tklib can be upgraded without breaking this detection (it appears it is solely for *detection*, not runtime).
The makefiles used -L flags for the local builddir and then -l to find libs therein. That's fragile if -L get mis-ordered or the libs get mis-built (or built in an unexpected order). Instead, hardcode paths to the actual library files.

staden: build-time portability vs tklib and local-lib linking

---

10.9-libcxx/stable/main/finkinfo/devel/astng-py.info

This fixes FTBFS on -py3x and has no effect on -py2x. See http://bindist.finkproject.org/10.13/logs/astng-py34_0.24.3-1_71c13179f47da313f6035b043b5b50c3.log

astng-py3x: call '2to3' with fink prefix and match pythonvariant

---

10.9-libcxx/stable/main/finkinfo/games/chocolate-doom.info
10.9-libcxx/stable/main/finkinfo/games/chocolate-doom.patch

@pierrehenri220 this is yours. I confirmed the bindist build error on my 10.13 and that this upstream patch allows building. There are newer upstream releases in this major-version series and also a new major-version series that I did not test.

chocolate-doom: upstream fix for FTBFS against current libsamplerate

---

10.9-libcxx/stable/main/finkinfo/sci/viennarna-10.9.info

The Type/Distribution was attempting to tie the build results to the
perl version (based on the OS X version) but the result was that the
same %n-%v-%r would use different installation pathnames for different
build-systems. That breaks policy. Instead, separate .info for each
perlversion, so each can have different %r, with bonus of simplifying
the Type and Distribution fields. Now when user moves to newer OS X,
the package self-identifies as needing to be updated.

viennarna: Separate .info and revision for each different platform-perl version

---

10.9-libcxx/stable/main/finkinfo/sci/convertall.info

Updated convertall to latest upstream version.  Updated dependencies to qt5 as required by latest upstream.  Built on macOS 10.13 with fink -m rebuild convertall.  Functionally tested with no obvious errors.

Convertall update

---

10.9-libcxx/stable/main/finkinfo/libs/perlmods/dbi-pm.info

Updated dbi-pm to latest upstream version.  Builds with fink -m on macOS 10.13.

updated dbi-pm to latest upstream version

---

10.9-libcxx/stable/main/finkinfo/libs/npth.info

Fixes buld failure reported on fink-beginners

npth: builddepend on automake1.15

---

10.9-libcxx/stable/main/finkinfo/database/tora.info

Same build transcript for the pg update.
f-p-p had a ton of warnings about files not recognized by dpkg and f-p-p didn't recognize because they were source-distro but in a sister subdir to the one where it was running. f-p-p isn't so smart about out-of-source or even build-subdir setups, so just run it from the main builddir.

tora: switch pg94->pg96; improve f-p-p use

---

10.9-libcxx/stable/main/finkinfo/sci/gdcm.info
10.9-libcxx/stable/main/finkinfo/sci/gdcm.patch

Now works with java9.
The current v2.6.1 release needs java5, which is incompatible with java9. v2.6.9 uses java7.
It also now builds the manpages, but can be disabled w/ a simple configure flag.
This is the last 2.6.x release.

gdcm26 2.6.9

---

10.9-libcxx/stable/main/finkinfo/libs/fltk13-aqua.info
10.9-libcxx/stable/main/finkinfo/libs/fltk13-aqua.patch

Upstream now says it explicitly supports 10.11-10.13.
Refresh patch due to upstream changes.
Clean PatchScript of commands that no longer do anything (carried over from long ago versions).

fltk13-aqua 1.3.4

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pyephem-py.info
10.9-libcxx/stable/main/finkinfo/sci/xephem.info
10.9-libcxx/stable/main/finkinfo/sci/xephem.patch

Updated xephem to latest upstream version.  Builds on macOS 10.13 with "fink -m xephem".  Functionally tested.
Update:
Whoops - I just realized that this branch didn't have the updated maintainer email address.  I'm not sure how to sort this out now that I have already made the Pull Request.  The maintainer email needs to be khorton02@gmail.com

updated xephem to latest upstream version

---

10.9-libcxx/stable/main/finkinfo/devel/rcs.info
10.9-libcxx/stable/main/finkinfo/devel/rcs.patch

Per [Fink-users] fink rcs broken on latest High Sierra

rcs: standard 10.13 fix for gnulib vasnprintf

---

10.9-libcxx/stable/main/finkinfo/graphics/pil-py.info

Debian bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=879788
Imaging.h #includes ImagingUtils.h, so it needs to be installed. This is Debian's fix:
````
install -o root -g root -m 644 \
src/libImaging/Imaging.h \
src/libImaging/ImagingUtils.h \
src/libImaging/ImPlatform.h \
src/libImaging/ImDib.h \
debian/python-pil/usr/include/python$*
````
which I adapted.

pil-py: Install headers #included by own Imaging.h.

---

10.9-libcxx/stable/main/finkinfo/devel/astroid-py.info
10.9-libcxx/stable/main/finkinfo/devel/pylint-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/isort-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/lazy-object-proxy-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/wrapt-py.info

This is bringing `pylint-py` up to date to the latest upstream `1.8.4` and adds/updates missing dependencies for `type_pkg[python] = 36`.
Built and tested for python 2.7-3.6 on 10.12 and 10.13 - 3 test failures on Python 3.x, > 222 (basically the entire test_stdlib) mostly unicode-related on 2.7.14.
Changed names of versioned executables to standard -py%type_pkg[python] scheme (pylint-gui no longer included). 2to3 treatment of sources no longer required. Added cleanup of byte-compiled files to InstallScript.

Pylint update (including dependencies for py36)

---

10.9-libcxx/stable/main/finkinfo/games/trackballs.info
10.9-libcxx/stable/main/finkinfo/games/trackballs.patch

@microtherion 
On 10.13, trackballs fails to build with this error:
```
g++ -DLOCALEDIR=\"/sw/share/locale\" -DHAVE_CONFIG_H -I. -I.. -DSHARE_DIR=\"/sw/share/trackballs\" -DPACKAGE=\"trackballs\" -DVERSION=\"1.1.4\"  -I/sw/include -I/opt/X11/include  -g -g -O2 -I/sw/include -I/sw/include -D_THREAD_SAFE  -I./ -I../ -DDEFAULT_RESOLUTION=1 -MT trackballs-glHelp.o -MD -MP -MF .deps/trackballs-glHelp.Tpo -c -o trackballs-glHelp.o `test -f 'glHelp.cc' || echo './'`glHelp.cc
glHelp.cc:132:13: error: 'abs' is missing exception specification 'throw()'
inline Real abs(Real v) {return v>0.0?v:-v;}
```
The original SF trackballs has been discontinued, but an active fork at https://trackballs.github.io/ has the patch needed to fix the error.

trackballs: Apply upstream patch to build on 10.13

---

10.9-libcxx/stable/main/finkinfo/gnome/gnome-icon-theme.info

Update gnome-icon-theme to 2.31.0, the last of the 2.x series.
Only substantial change is to remove the chunk modifying the `allow_rendering` flag because that's no longer present in the source code and there's no indication of any git still being used in the code.

Gnome icon theme 2.31.0

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/entrypoints-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/keyring-py.info

Adds entrypoints-py so that keyring-py can depend on it. As of the update to keyring-py 12.2.0, the keyring command and library fail at startup with:
```
% /sw/bin/keyring
Traceback (most recent call last):
File "/sw/bin/keyring", line 6, in <module>
from pkg_resources import load_entry_point
File "/sw/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
@_call_aside
File "/sw/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
f(*args, **kwargs)
File "/sw/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/sw/lib/python2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_master
ws.require(__requires__)
File …
```

keyring-py 12.2.0 depends on entrypoints-py

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/isort-py.info

In `4.3.4` `isort-py` (updated in #130) added an import from `concurrent.futures`; the `py27` variant needs the backport in `futures-py` for this. 3 test failures remaining.

Added missing futures-py dependency to Python2.7 variant of isort-py

---

10.9-libcxx/stable/main/finkinfo/devel/pylint-py.info

Without this module installed, pylint fails at startup with
```
Traceback (most recent call last):
File "/sw/bin/pylint", line 6, in <module>
from pkg_resources import load_entry_point
File "/sw/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
@_call_aside
File "/sw/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
f(*args, **kwargs)
File "/sw/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/sw/lib/python2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_master
ws.require(__requires__)
File "/sw/lib/python2.7/site-packages/pkg_resources/__init__.py", line 963, in require
needed = …
```

pylint: depend on singledispatch-py for python 2.7

---

10.9-libcxx/stable/main/finkinfo/utils/clamav.info

New upstream version 0.100 of clamav. Cleanup the package to remove obsolete stuff and cleanup dependencies.

New upstream version and some cleanup of the package for clamav

---

10.9-libcxx/stable/main/finkinfo/database/psycopg2-py.info
10.9-libcxx/stable/main/finkinfo/database/psycopg2-py.patch

psycopg2-py update:
- update to latest upstream 2.7.4
- add python 3.6 variant + additional patch for python 3.6 tests
- switch Postgres 9.4 to 10
Package testet "fink -m build" and with python 2.7, 3.4, 3.5 and 3.6 and postgresql server 10
For the -m maintainer tests to work, you need to run these two commands first:
sudo -u postgres createuser fink-bld
sudo -u postgres createdb psycopg2_test --owner=fink-bld
@schwehr please check and approve the psycopg2-py update, thanks.

psycopg2-py: update to 2.7.4; add python36 variant; switch pg94->pg10

---

10.9-libcxx/stable/main/finkinfo/sci/eccodes.info
10.9-libcxx/stable/main/finkinfo/sci/grib-api.info

This covers the upstream updates to two APIs from ECMWF:
GRIB API 1.26.1 (deprecated but still updated)
ECCODES 2.7.3 (replacement for GRIB API)

Updates to ECMWF API software

---

10.9-libcxx/stable/main/finkinfo/languages/ucblogo.info
10.9-libcxx/stable/main/finkinfo/languages/ucblogo.patch

As found by the bindist http://bindist.finkproject.org/10.13/logs/ucblogo_6.0-1_c644de3780c94d41addb76db2c7a8d50.log the autoconf2.13-era ./configure script broke again. While fixing it, I noticed missing ncurses deps, and added fink-package-precedence to help track it. Debian's ucblogo package had some useful patches (including some we already had), so I pulled them in also.

ucblogo: Fix FTBFS, add debian patches, update deps

---

10.9-libcxx/stable/main/finkinfo/libs/readline6.info
10.9-libcxx/stable/main/finkinfo/libs/readline7.info

Should we switch to "Version: X.Y.plZ" the next time we jump to a new X or Y to clarify that our "Z" is what upstream calls "patchlevel" rather than a teensy-version? Debian does not even include this specific value in its version or revision (merely increments revision just like any other packaging change).

Readline update (upstream patchlevel 5)

---

10.9-libcxx/stable/main/finkinfo/database/postgresql94.info
10.9-libcxx/stable/main/finkinfo/database/postgresql95.info
10.9-libcxx/stable/main/finkinfo/database/postgresql96.info

the PR updates the pg 9.x packages to the latest upstream version
postgresql94: Update to 9.4.18 
postgresql96: Update to 9.5.13 
postgresql96: Update to 9.6.9 
and the latest info file changes from pg10 (using a variant to minimize diffs among the version).
All versions testet with fink -m build.

Postgresql9x: : update to latest upstream + backport info file changes from pg10

---

10.9-libcxx/stable/main/finkinfo/libs/readline7.info

I rebuilt all rdeps on readline7 (except intermediate libversions where I only built the earliest and latest) and there were no differences in detection. Saved a minute of build time, and hey, what good are static libs anyway (esp. noting that this is the active release series, so prone to changes). I used this rebuild as an opportunity to switch to ```Version: X.Y.plZ``` for upstream X.Y upstream patchlevel Z, as discussed in PR #178

readline7: scrap static lib; switch to '.plX' versioning (PR#178)

---

10.9-libcxx/stable/main/finkinfo/text/ghostscript.info
10.9-libcxx/stable/main/finkinfo/text/ghostscript.patch

This is an update for the ghostscript, from upstream version 9.21 to 9.23.
This removes the dependency on libcms2.
Maintainer switched from "none" to myself.

ghostscript-9.23-1

---

10.9-libcxx/stable/main/finkinfo/crypto/gnupg2.info
10.9-libcxx/stable/main/finkinfo/crypto/libassuan2.info
10.9-libcxx/stable/main/finkinfo/crypto/libgpg-error.info
10.9-libcxx/stable/main/finkinfo/crypto/libgpgme11-1.9-shlibs.info

Updates to gcrypt libraries and programs. Ironically, this first started with an update to libgcrypt20, but version 1.8.3 hangs during the tests, so I didn't update it. All others tested on 10.11.

Gcrypt updates

---

10.9-libcxx/stable/main/finkinfo/net/isync.info

New version clears a few compiler warnings vs old, and switching openssl100->openssl110 clears a few more without adding any.

isync: new version; openssl update

---

10.9-libcxx/stable/main/finkinfo/sci/netcdf-cxx4.info

Update Source to match the FTP Download site also used for other netCDF packages.
This fixes an issue reported by nieder on 22 May and dmacks on 4 July, i.e. that the checksum did not match the source. That is because the checksum of the tarball put on the netCDF GitHub pages is not identical to that put on the official Download pages.

netcdf-cxx4-4.3.0-1: Fix checksum issue

---

10.9-libcxx/stable/main/finkinfo/languages/setuptools-tng-py.info

I just added python 3.7 and virtually every pymod will need this before they can be updated.

New upstream setuptools 39.2.0 and add py37 variant

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/nose-py.info
10.9-libcxx/stable/main/finkinfo/sci/numpy-py.info

`py37` variants of `numpy-py` (requiring update to `1.14.5`) and its `TestDepends` `nose-py37`.
Also requires `setuptools-tng-py37` from #192.

Adding Python 3.7 support to Numpy

---

10.9-libcxx/stable/main/finkinfo/graphics/optipng.info

Fink's current 0.7.6 fails to build on 10.13 for me and also in the [bindist for 10.13](http://bindist.finkproject.org/10.13/logs/optipng_0.7.6-1_9ceab30cd68c7fb77253fc36d942c5b6.log). I don't see an error in the 10.11/10.12 bindist. Upstream has a [bug report about it](https://sourceforge.net/p/optipng/patches/9/) that says 10.13 being different than older versions, but that 10.12 would be like 10.13?
The attached upgrades to the new 0.7.7 upstream (which also has some major security fixes), and builds for me on 10.13. Probably should get someone with 10.12 (I don't have it), and maybe something older to test-build, or else have this specifically tagged for 10.13 only for now.

optipng: new version

---

10.9-libcxx/stable/main/finkinfo/text/discount.info

discount 2.2.3a to solve clang build failures

---

10.9-libcxx/stable/main/finkinfo/devel/gir2pascal.info

gir2pascal converts gobject-introspection (*.gir) xml files into Pascal files.

gir2pascal: new package

---

10.9-libcxx/stable/main/finkinfo/languages/pip-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/atomicwrites-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/attrs-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/beaker-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/coverage-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/decorator-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/hypothesis-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/invoke-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/jinja2-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/linecache2-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/markupsafe-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/mock-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/more-itertools-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pbr-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pluggy-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/py-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pygments-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pytest-mock-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pytest-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pytest-relaxed-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pytest-runner-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/setuptools-scm-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/six-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/tox-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/tox-py.patch
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/traceback2-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/unittest2-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/virtualenv-py.info
10.9-libcxx/stable/main/finkinfo/text/docutils-py.info

Updates to `pytest-3.6.2` and `tox-3.0.0` with added `py37` variants, plus their `Depends`, `TestDepends` and their respective `TestDepends`.
Unfortunately `3.6.2` brings circular dependency madness to a new level, requiring a new module `invoke` which depends on a `pytest-relaxed` extension, which in turn explicitly requires `pytest<3.3`! I have taken the hard way out of this by hacking `pytest-relaxed-py` to accept `pytest-py-3.6`; this introduces some failures in its own tests, but allows the `invoke-py` test suite to complete successfully.
Builds with tests enabled without prior installation naturally are largely impossible; a working update path with subsequent testing should be
```
fink --validate update tox-py37 pytest-mock-py37
fink -m rebuild atomicwrites-py37 attrs-py37 …
```

Pytest/tox and dependencies updates and Python 3.7 variants

---

10.9-libcxx/stable/main/finkinfo/utils/unrar.info

Removal of some FLAGS. Their effect is now taken care of by upstream and they are no longer required.

unrar: Update to new upstream version (5.6.5)

---

10.9-libcxx/stable/main/finkinfo/database/postgresql10.info
10.9-libcxx/stable/main/finkinfo/database/postgresql94.info
10.9-libcxx/stable/main/finkinfo/database/postgresql94.patch
10.9-libcxx/stable/main/finkinfo/database/postgresql95.info
10.9-libcxx/stable/main/finkinfo/database/postgresql96.info

Update for postgresql packages to latest upstream version
postgresql94 update to 9.4.19
postgresql95 update to 9.5.14
postgresql96 update to 9.6.10
postgresql10 update to 10.5
Update includes security fixes:
CVE-2018-10925  -Memory disclosure and missing authorization in INSERT ... ON CONFLICT DO UPDATE.
CVE-2018-10915 - Certain host connection parameters defeat client-side security defenses

postgresql updates Aug. 2018

---

10.9-libcxx/stable/main/finkinfo/database/redis.info

update to latest upstream version 4.0.11 for the redis package.
The update fixes important security issues related to the Lua scripting engine (CVE-2018-11218
CVE-2018-11219 ):
https://github.com/antirez/redis/issues/5017 
http://antirez.com/news/119
@krbullock please check the package as the package maintainer.

redis 4.0.11

---

10.9-libcxx/stable/main/finkinfo/languages/setuptools-tng-py.info
10.9-libcxx/stable/main/finkinfo/languages/wheel-py.info

In addition:
- change source to files.pythonhosted.org
- add py37 variant of wheel
- update docfiles of wheel

wheel & setuptools-tng: update to upstream

---

10.9-libcxx/stable/main/finkinfo/base/expat1.info

Per https://sourceforge.net/p/fink/mailman/message/36396563/
Should we scrap the static lib? I've left it due to inertia, but .a are generally unused when there is a .dylib (and fully static linking isn't even possible regardless)

expat1: new version

---

10.9-libcxx/stable/main/finkinfo/devel/ddd.info
10.9-libcxx/stable/main/finkinfo/devel/ddd.patch

ddd fails to build on Xcode9 with unknown type name a_class.
This is the upstream submission to fix it.

Fix ddd build on Xcode9

---

10.9-libcxx/stable/main/finkinfo/utils/duplicity.info
10.9-libcxx/stable/main/finkinfo/utils/duplicity.patch

Updated version, and MD5 hash for latest release with bug patch to duplicity 0.7.18.1 released on 2018-08-27

Version Update for Duplicity

---

10.9-libcxx/stable/main/finkinfo/text/ghostscript.info
10.9-libcxx/stable/main/finkinfo/text/ghostscript.patch

This also got rid of one of our patches, the one on the link to an old documentation location. This is now fixed upstream, as expected and discussed during Pull Request #188.

ghostscript-9.24-1: Upstream update

---

10.9-libcxx/stable/main/finkinfo/crypto/m2crypto-py.info

m2crypto-pyXX: new version, switch to openssl110

m2crypto-pyXX: new version, switch to openssl110

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/bcrypt-py.info

Add builddep on setuptools-tng-py, and deps on cffi-py and six-py

bcrypt-py: new upstream release 3.1.4

---

10.9-libcxx/stable/main/finkinfo/database/libspatialite7.info

This is to avoid that gdal2 links to both libgeos3.6.1 (by itself) and the libgeos3.5.1 (though libspatiallte7)

libspatialite7: changed dependency from libgeos3.5.0 to libgeos3.6.1

---

10.9-libcxx/stable/main/finkinfo/libs/libspatialindex2-shlibs.info
10.9-libcxx/stable/main/finkinfo/libs/libspatialindex3-shlibs.info
10.9-libcxx/stable/main/finkinfo/libs/libspatialindex4-shlibs.info

Scrap the BDO packages of unused old libversions (retain -shlibs per policy), turn off static libs, and misc packaging cleanups.
@babayoshihiko, these are yours.

libspatialindex cleanup

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pytz-py.info

Update to newer upstream version (2018.5). Adding py37 variant gives fails in tests, which do not look like a big problem, but i could not fix them.
Log:
```
...
FAIL: pytz/tests/../../README.txt
Doctest: README.txt
----------------------------------------------------------------------
Traceback (most recent call last):
File "/sw/lib/python3.7/doctest.py", line 2198, in runTest
raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for README.txt
File "pytz/tests/../../README.txt", line 0
----------------------------------------------------------------------
File "pytz/tests/../../README.txt", line 183, in README.txt
Failed example:
tz.utcoffset(normal, is_dst=True)
Expected:
datetime.timedelta(-1, 77400)
Got:
datetime.timedelta(days=-1, …
```

pytz-py: Upstream update.

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pypubsub3-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pypubsub4-py.info

Version 4 does not build on python 2.7. Therefore, version 3 for that.

pypubsub-py: new package

---

10.9-libcxx/stable/main/finkinfo/crypto/libsodium13.info
10.9-libcxx/stable/main/finkinfo/crypto/libsodium23.info

includes conflicts and replaces with older versions.

libsodium: update to new upstream version (1.0.16)

---

10.9-libcxx/stable/main/finkinfo/languages/pyqt5-mac-py.info
10.9-libcxx/stable/main/finkinfo/languages/sip-py.info
10.9-libcxx/stable/main/finkinfo/languages/sip-py.patch

In addition: line numbers in patch files adjusted.

sip-py: update to upstream; add py37 variant

---

10.9-libcxx/stable/main/finkinfo/libs/libuv1.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/gevent-py.info

gevent-pyXX FTBFS for me (same as on bindist) where I have libuv1-1.8.0-1 installed with errors related to unknown API in libuv1, but gevent-pyXX has no dependencies on libuv1. Looks like it autodetects, and if so actually needs a newer version. Pushing libuv1 to its latest version allows gevent-pyXX to build against it, so I set versioned dependencies accordingly.
I did not investigate what version first added the needed API to be able to set a slightly looser dependency (but since fink has no intermediate versions, who cares). I also did not investigate whether there is a way to disable libuv detection.

gevent-py fix; libuv1 update

---

10.9-libcxx/stable/main/finkinfo/sci/eccodes.info

This is a simple update due to upstream update from 2.8.2 to 2.9.0.
No other changes needed.
Built and tested with "fink -m build" on 10.14

eccodes-2.9.0-1

---

10.9-libcxx/stable/main/finkinfo/database/sqlalchemy-py.info

Details:
- Update version, server host and MD5
- add py37 variant
- add doc files
- add note about tests

sqlalchemy-py: update to newer upstream version (1.2.12) + py37 variant

---

10.9-libcxx/stable/main/finkinfo/text/ghostscript.info
10.9-libcxx/stable/main/finkinfo/text/ghostscript.patch

This is the update for ghostscript from 9.24 to 9.25.
Built and test on 10.14 with "fink -m build"

ghostscript-9.25-1

---

10.9-libcxx/stable/main/finkinfo/sci/grib-api-fortran.info
10.9-libcxx/stable/main/finkinfo/sci/grib-api.info

This is a simple upstream update from 1.26.1 to 1.27.0.
(I missed that update on grib-api-fortran though so that jumps one version).
Built and tested with "fink -m build"
Note 1:
This does not need the complicated install_name_tool stuff as in eccodes (see PR #231)
This is because GRIB-API is not built with cmake.
Note 2:
I removed the old packages first to be sure the test was done with the just built executables (before installing in %p)

grib-api-1.27.0-1 (and grib-api-fortran-1.27.0-1)

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/gsutil-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pysocks-py.info
10.9-libcxx/stable/main/finkinfo/web/socksipy-py.info

The two packages both install a socks.py which obviously conflicts.
gsutil-py is the only package that uses socksipy so switch it to pysocks to avoid the conflict. See https://github.com/fink/fink-distributions/issues/237

pysocks-py is a newer fork of socksipy-py

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/cssselect-py.info
10.9-libcxx/stable/main/finkinfo/text/lxml-py.info

Updating `lxml-py` to 4.2.5 and adding a `py37` variant as discussed in #288 - this reduces the no. of skipped tests in `html5lib-py` by ~ 4000-5000.
Also adding an update of `cssselect-py` with a near-circular dependency: cssselect tests critically depend on lxml, while some lxml tests (possibly only one) require cssselect, but will automatically be skipped otherwise. I have therefore just made `cssselect-py` a `Recommends` of `lxml-py` and a `TestDepends` vice-versa.
lxml's `test.py` insists on loading the module from the `src/lxml` path, which forced me to run an additional inplace build. One might perhaps just manually install the `*.so` files from `build/lib*`, but this seemed a bit hackish to me...

lxml-py update and Python 3.7 version

---

10.9-libcxx/stable/main/finkinfo/libs/lz4.info

Adding the docs directory to lz4.

lz4: update to new upstream version (1.8.3)

---

10.9-libcxx/stable/main/finkinfo/languages/pyqt5-mac-py.info

This minimal patch fixes the issue with missing enum34-py27 dependence from the mailing list for the py27 variant.
Other potential issues are neglected at this point.

pyqt5-mac-py: fix issue with py27 variant

---

10.9-libcxx/stable/main/finkinfo/sci/wxmplot-py.info

Plotting widgets for wxPython with matplotlib. No py37 variant, since matplotlib-py37 is still missing.

wxmplot-py: new package

---

10.9-libcxx/stable/main/finkinfo/database/postgresql10.info
10.9-libcxx/stable/main/finkinfo/database/postgresql94.info
10.9-libcxx/stable/main/finkinfo/database/postgresql95.info
10.9-libcxx/stable/main/finkinfo/database/postgresql96.info

postgresql updates November 2018:
- Update PG 10  to 10.6
- Update PG 9.6  to 9.6.11
- Update PG 9.5  to 9.5.15
- Update PG 9.4  to 9.4.20
Upstream fixed build issues on 10.14 for all supported versions ( Issue #291 ).
Contains preparation for new major version postgresql 11.

postgresql updates Nov  2018

---

10.9-libcxx/stable/main/finkinfo/net/libcurl4.info

The files for the copy in the patch script are no longer in /usr/include.

libcurl4: fix include prefix for 10.14

---

10.9-libcxx/stable/main/finkinfo/sci/delila-bundle.info

The binary split replaces the system binary split with a completely different functionality. This prevents building qt4-base-mac and maybe more.

delila-bundle: rename binary split

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/sphinx-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/sphinxcontrib-websupport-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/sphinxcontrib-websupport-py.patch

add py37 variant
add new package sphinxcontrib-websupport-py.
add dependencies and test-dependencies as they show up during the build.

Sphinx-py: update to newer upstream version (1.8.1)

---

10.9-libcxx/stable/main/finkinfo/languages/python27.info
10.9-libcxx/stable/main/finkinfo/languages/python34.info
10.9-libcxx/stable/main/finkinfo/languages/python35.info
10.9-libcxx/stable/main/finkinfo/languages/python36.info
10.9-libcxx/stable/main/finkinfo/languages/python37.info

Updated python27, python34, python35, python36 and python37 to build with fink installed versions of readline6 and db4 ahead of the SDK versions for MacOS 10.14.X.

python2 & 3 on MacOS 10.14

---

10.9-libcxx/stable/main/finkinfo/database/postgresql10.info
10.9-libcxx/stable/main/finkinfo/database/postgresql94.info
10.9-libcxx/stable/main/finkinfo/database/postgresql95.info
10.9-libcxx/stable/main/finkinfo/database/postgresql96.info

Fix for correctly setting the isysroot  with Xcode command line tools only  installations.
This should solve the build issues for 10.14 (Issue #291 )

postgresql: fix for 10.14 build

---

10.9-libcxx/stable/main/finkinfo/sci/fftw3.info

This update is three-fold:
- Make things work on Mojave: this included adding `xcrun` to get the SDK path for `/usr/include`
- Removed a switch for the support of powerpc, which does not apply to the `10.9-libcxx` tree, as powerpc is no longer supported.
- Update to the latest FFTW3 version (3.3.8 from May 2018)
Run and tested on 10.14.2 with Command Line Tools 10.1 and `fink -m build`

fftw3-3.3.8.1: upstream update and make things work on Mojave

---

10.9-libcxx/stable/main/finkinfo/web/wget.info

This is a simple upstream update for wget. Version 1.20.1 was released Dec 2018.
Built, tested, and run on Mac OS 10.14.2 with Command Line Tools 10.1 and `fink -m build`

wget-1.20.1-1: Upstream update

---

10.9-libcxx/stable/main/finkinfo/sci/grib-api-fortran.info
10.9-libcxx/stable/main/finkinfo/sci/grib-api.info

This is an update to the grib-api and grib-api-fortran packages.
Upstream version 1.28.0, released in December, is the end of the line. The GRIB API will no longer be supported by ECMWF.
We already have the alternative in Fink: eccodes.
Built, tested, and run on Mac OS 10.14.2 with Command Line Tools 10.1 and `fink -m build`.

grib-api-1.28.0-1 and grib-api-fortran-1.28.0-1: FINAL upstream update

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/sphinx-py.info

This PR is twofold:
- Add the dependency on typing-py (for python < v3.5). It was added to the dependencies for the test suite, but not for the package itself.
- En passant, updated to upstream version 1.8.4, released 3 Feb 2019.

sphinx-py-1.8.4-1: Add missing dependency on typing-py and upstream update

---

10.9-libcxx/stable/main/finkinfo/web/wget.info

This is an update since a user found that the binary package was linked against libpcre2 rather than the intended libpcre1.
This is now avoided by adding `--enable-pcre --disable-pcre2` to `configure`.
Built and tested on Mac OS 10.14.2 with Command Line Tools 10.1, with both libpcre1 and libpcre2 installed. Only libpcre1 was now linked as required.

wget-1.20.1-2: Avoid linking libpcre2 (use libpcre1 always)

---

10.9-libcxx/stable/main/finkinfo/languages/python37.info
10.9-libcxx/stable/main/finkinfo/languages/python37.patch
10.9-libcxx/stable/main/finkinfo/languages/sbcl-x86_64.info
10.9-libcxx/stable/main/finkinfo/languages/sbcl.patch

- Builds sbcl (Steel Bank Common Lisp) on MacOS v10.14.3.
- Reduces warnings building python v3.7 with Xcode compiler.

sbcl v1.4.16

---

10.9-libcxx/stable/main/finkinfo/sci/gdl.info

This is a simple update that helps to find zlib on Mojave using `xcrun`.
Built and tested on 10.14.3 with Command Line Tools 10.1 and `fink -m build`.
PS: I was not able to get either upstream 0.9.8 or 0.9.9 compiled due to an incompatibility with `plplot` in `src/gdlgstream.hpp`. It is true that Fink's `plplot-5.9.6-5` is very much out of date: upstream is now at 5.14.0.

gdl-0.9.7-3: Make configuration work for Mojave (find zlib)

---

10.9-libcxx/stable/main/finkinfo/database/postgresql10.info
10.9-libcxx/stable/main/finkinfo/database/postgresql10.patch
10.9-libcxx/stable/main/finkinfo/database/postgresql94.info
10.9-libcxx/stable/main/finkinfo/database/postgresql95.info
10.9-libcxx/stable/main/finkinfo/database/postgresql96.info

the PR updates the postgresql packages to the latest upstream version.
- postgresql10 update to 10.7
- postgresql96 update to 9.6.12
- postgresql95 update to 9.5.16
- postgresql94 update to 9.4.21

postgresql updates februar 2019

---

10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-rgdal-r.info

$ dpkg -L cran-rgdal-r35
/.
/sw
/sw/lib
/sw/lib/R
/sw/lib/R/3.5
/sw/lib/R/3.5/site-library
/sw/lib/R/3.5/site-library/rgdal
/sw/lib/R/3.5/site-library/rgdal/ChangeLog
/sw/lib/R/3.5/site-library/rgdal/data
/sw/lib/R/3.5/site-library/rgdal/data/GridsDatums.rda
/sw/lib/R/3.5/site-library/rgdal/data/nor2k.rda
/sw/lib/R/3.5/site-library/rgdal/DESCRIPTION
/sw/lib/R/3.5/site-library/rgdal/doc
/sw/lib/R/3.5/site-library/rgdal/doc/index.html
/sw/lib/R/3.5/site-library/rgdal/doc/OGR_shape_encoding.pdf
/sw/lib/R/3.5/site-library/rgdal/doc/OGR_shape_encoding.R
/sw/lib/R/3.5/site-library/rgdal/doc/OGR_shape_encoding.Rnw
/sw/lib/R/3.5/site-library/rgdal/etc
/sw/lib/R/3.5/site-library/rgdal/etc/obj_with_comments.RData
/sw/lib/R/3.5/site-library/rgdal/etc/obj_without_comments.RData …

Add cran rgdal for R-3.5

---

10.9-libcxx/stable/main/finkinfo/languages/perl5162.info
10.9-libcxx/stable/main/finkinfo/languages/perl5182.info
10.9-libcxx/stable/main/finkinfo/text/texi2html-10.13.info
10.9-libcxx/stable/main/finkinfo/text/texi2html-10.14.info
10.9-libcxx/stable/main/finkinfo/text/texi2html-perl5162-deployment_target.patch
10.9-libcxx/stable/main/finkinfo/text/texi2html-perl5162.info
10.9-libcxx/stable/main/finkinfo/text/texi2html-perl5162.patch
10.9-libcxx/stable/main/finkinfo/text/texi2html.info

Creating a private perl5162 interpretter (hidden in lib/texi2html) for texi2html to use on platforms where apple doesn't supply perl5162 and we don't feel like having to continue supporting a full user-land perl5162 suite. See PR #339.

Texi2html onboard perl

---

10.9-libcxx/stable/main/finkinfo/utils/expect.info
10.9-libcxx/stable/main/finkinfo/utils/expect.patch

expect-5.45-205: Needed update to find tcltk (private) headers in Fink tree.
Build and tested on MacOS 10.14.3 with command line tools 10.1

expect-5.45-205: Needed update to find tcltk (private) headers

---

10.9-libcxx/stable/main/finkinfo/sci/netcdf-c11.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-c13.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-c15.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-c7.info

Library version number changed from `libnetcdf.13.dylib` to `libnetcdf.15.dylib`, hence new package.
When accepted, I'll forthwith update packages to link against `netcdf-c15-shlibs`, where appropriate.
Removed from configuration `--disable-cdf5` which was introduced in package version 4.6.1 because of bug; fixed since 4.6.2.
All versions built and tested with `fink -m build` on MacOS 10.14.3 with Command Line Tools 10.1.

netcdf-c15-4.6.3-1: upstream update and new library version

---

10.9-libcxx/stable/main/finkinfo/sci/netcdf-fortran7.info

Updated from version 4.4.4 to 4.4.5. En passant updated dependencies:
gcc7 -> gcc8
netcdf-c13 -> netcdf-c15.
Built and tested with `fink -m build netcdf-fortran7` on MacOS 10.14.3 with Command Line Tools 10.1

netcdf-fortran7-4.4.5-1: upstream and dependencies update

---

10.9-libcxx/stable/main/finkinfo/sci/nco.info

Updated from version 4.7.8 to 4.7.9. En passant updated dependencies:
* netcdf-c13 -> netcdf-c15
* removed BuildDepends on netcdf-bin since it is not used.
Built and tested with `fink -m build nco` on MacOS 10.14.3 with Command Line Tools 10.1

nco-4.7.9-1: upstream and dependency update

---

10.9-libcxx/stable/main/finkinfo/sci/eccodes.info
10.9-libcxx/stable/main/finkinfo/sci/eccodes.patch

Updated from version 2.10.0 to 2.12.0. En passant changed dependencies:
gcc7 -> gcc8
netcdf-c13 -> netcdf-c15
Removed dependencies on hdf5: they were not used.
Built and tested with `fink -m build eccodes` on MacOS 10.14.3 with Command Line Tools 10.1

eccodes-2.12.0: upstream and dependencies update

---

10.9-libcxx/stable/main/finkinfo/sci/gmt.info
10.9-libcxx/stable/main/finkinfo/sci/gmt5.info
10.9-libcxx/stable/main/finkinfo/sci/ncview.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-cxx4.info

This PR as a replacement for PR #375 and updates the dependencies netcdf-c13 -> netcdf-c15
In the following packages:
ncview
netcdf-cxx4
gmt5
gmt
All are built and tested with fink -m build on MacOS 10.14.3 with Command Line Tools 10.1

Various updates to NetCDF dependencies

---

10.9-libcxx/stable/main/finkinfo/sci/cdo.info
10.9-libcxx/stable/main/finkinfo/sci/cdo.patch

This updates `cdo` to version 1.9.6 and updates the following dependencies:
gcc7 -> gcc8
netcdf-c13 -> netcdf-c15
hdf5.10 -> hdf5.100.v1.10
Built and tested (both `cdo` and `cdo-openmp` on MacOS 10.14.4 with Command Line Tools 10.2
This replaces closed PR #357

cdo-1.9.6-1: upstream and dependency update

---

10.9-libcxx/stable/main/finkinfo/sci/eccodes.info
10.9-libcxx/stable/main/finkinfo/sci/eccodes.patch

Despite eccodes not using HDF5, its CMake system tries to find it in two places. One place was already commented out, the second was missed and is added in this patch.
This should allow building eccodes without unnecessary dependencies, irrespective of whether HDF5 is already installed.
See e-mail "phase compiling: eccodes-2.12.0-1 failed" to fink-beginners@lists.sourceforge.net and comment by @dhomeier in PR #373 
Built and tested on MacOS 10.14.3 with Command Line Tools 10.1

eccodes-2.12.0-2: Getting rid of searching for HDF5

---

10.9-libcxx/stable/main/finkinfo/devel/openmpi.info
10.9-libcxx/stable/main/finkinfo/sci/fftw3.info
10.9-libcxx/stable/main/finkinfo/sci/pgplot.info
10.9-libcxx/stable/main/finkinfo/sci/pgplot.patch
10.9-libcxx/stable/main/finkinfo/sci/wip.info

This updates four of the sci packages to use gcc8 instead of gcc7, i.e.:
fftw3
openmpi
pgplot
wip
pgplot also was patched to work with MacOS 10.14 (where there is no /usr/include).
Otherwise, it is a revision bump and replacement of `Type: gcc (7)` by `Type: gcc (8)` for all four packages.
Built and tested on MacOS 10.14.3 with Command Line Tools 10.1

Updated dependencies gcc7 -> gcc8

---

10.9-libcxx/stable/main/finkinfo/sci/gdl.info
10.9-libcxx/stable/main/finkinfo/sci/gdl.patch

Update to version 0.9.8.
Also include dependency update:
netcdf-c13 -> netcdf-c15
hdf5.10 -> hdf5.100.v1.10
(hdf5-cpp11 removed as headers are now all in hdf5.100.v1.10)
Additionally, changed introduction of SDK path, now depending on Darwin version, as suggested by @dhomeier in PR #375 
Built and tested on Mac OS 10.14.4 and Command Line Tools 10.2

gdl-0.9.8-1: upstream update

---

10.9-libcxx/stable/main/finkinfo/sci/lapack360.info
10.9-libcxx/stable/main/finkinfo/sci/lapack361.info
10.9-libcxx/stable/main/finkinfo/sci/lapack371.info
10.9-libcxx/stable/main/finkinfo/sci/lapack380.info
10.9-libcxx/stable/main/finkinfo/sci/lapack380.patch

I was unable to build the `lapack360` and upwards packages on case-sensitive HFS due to spelling/capitalisation errors in the .info files.
Also, from 3.6.1 to 3.7.1 various changes in the format of the `lapack*.pc.in` and `blas.pc.in` files were introduced, causing the existing `PatchScript`s to create .pc files with invalid `pkgconfig` paths.
Added fixes here plus update to the latest upstream version 3.8.0.

LAPACK fixes and update

---

10.9-libcxx/stable/main/finkinfo/sci/grib-api-fortran.info

Simple dependency update
Built and tested on MacOS 10.14.4 with Command Line Tools 10.2

grib-api-fortran-1.28.0-2: Update dependency gcc7 -> gcc8

---

10.9-libcxx/stable/main/finkinfo/net/telnet.info

Xcode 10 seems no longer to honor the *ROOT variables from the CompileScript and only uses their default values (/tmp/telnet/*).

Ugly hack for Xcode 10

---

10.9-libcxx/stable/main/finkinfo/text/epstool.info
10.9-libcxx/stable/main/finkinfo/text/epstool.patch

With the mirrors all offline I was unable to build the `epstool` package as the original source location has disappeared. It's new location has version `3.09`.

Epstool update to 3.09 and new source location

---

10.9-libcxx/stable/main/finkinfo/web/nginx.info

Update to latest stable nginx release.
Fix library detection so that it doesn't search/#include /usr/include headers but then link %p libraries.
Fixes #395.

nginx 1.14.2

---

10.9-libcxx/stable/main/finkinfo/devel/lazarus-doc.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-carbon.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-cocoa-32bit.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-cocoa.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-gtk2.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-qt4.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-qt5.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-win32.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-win64.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-wince-arm.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-wince-i386.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus.info
10.9-libcxx/stable/main/finkinfo/devel/qt5pas.info

Includes qt5pas. All builds now on 10.14.

Lazarus: Update to new upstream version (2.0.2)

---

10.9-libcxx/stable/main/finkinfo/sci/cernlib2006.info
10.9-libcxx/stable/main/finkinfo/sci/patchy4.info

Update CERNLIB and patchy to use gcc8 instead of gcc6.

Compile CERNLIB with gcc8

---

10.9-libcxx/stable/main/finkinfo/net/libzmq6-shlibs.info
10.9-libcxx/stable/main/finkinfo/net/zmq-py.info

the new version needs libsodium23, which is in its own update branch.
zmq-py: update source URL.

zmq-py, libzmq6: update, add py37 variant

---

10.9-libcxx/stable/main/finkinfo/languages/python27.info
10.9-libcxx/stable/main/finkinfo/languages/python37.info

Replaced `-isysroot $SDK_PATH` by `-I$SDK_PATH/usr/include` in CFLAGS setting.
This is because `-isysroot` appears to suppress `-I%p/include`.
The same approach was used in `python34.info`, `python35.info`, `python36.info`
This fixed issue #363.

python-2.7.16-2 and python-3.7.2-3: Avoid failing module builds on 10.14

---

10.9-libcxx/stable/main/finkinfo/libs/libcdio13-shlibs.info
10.9-libcxx/stable/main/finkinfo/libs/libcdio15-shlibs.info

libcdio13 and libcdio15 FTBFS on recent 10.x because of a restrictive regexp in ./configure. Fink's patch was not sufficient on the most recent 10.x. Here's upstream's (== libcdio19) latest tweak.

libcdio13/15: fix detection of recent OS X

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/semanticversion-py.info
10.9-libcxx/stable/main/finkinfo/web/django-localflavor-py.info

Leftover fixes to django-localflavor-py tests and semanticversion-py BuildDepends

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/appnope-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/backcall-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/backports.shutil-get-terminal-size-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/bleach-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/entrypoints-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/ipython-genutils-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/jdcal-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/jedi-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/nose-warnings-filters-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pandocfilters-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/parso-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pickleshare-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/prometheus-client-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/prompt-toolkit-py-1.0.15.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/prompt-toolkit-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pygraphviz-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/send2trash-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/testpath-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/traitlets-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/wcwidth-py.info
10.9-libcxx/stable/main/finkinfo/web/selenium-py.info
10.9-libcxx/stable/main/finkinfo/web/zopeevent-py.info
10.9-libcxx/stable/main/finkinfo/web/zopeinterface-py.info

Starting a new PR for the IPython/Jupyter/Notebook infrastructure, since #164 has become quite unmanageable with half of the packages already changed elsewhere or committed independently to `master` by now.
This PR contains only updates/Python3.7 extensions and new submissions without any dependencies on the new `ipython-py` package itself, so for this part there should not be any problems with circular (test) dependencies. Enabled strict testing where possible, except for `pygraphviz-py`, which fails on ~24 tests and just returns a warning (`exit 1`).

Ipython 5+ and Notebook Depends

---

10.9-libcxx/stable/main/finkinfo/sci/openblas.info
10.9-libcxx/stable/main/finkinfo/sci/openblas.patch
10.9-libcxx/stable/main/finkinfo/sci/scipy-py.info

The packaging in this PR is not necessarily finalised, but I am putting this already up for discussion.
Rationale: updating the existing `scipy-py` package to upstream 1.1.0 introduces about a dozen segfaults in the test suite; from 1.2.0 on Scipy no longer officially supports building against Accelerate due to its outdated API - trying to do so introduced another bunch of segfaults in the `linalg` tests. Experimenting with reintroducing ATLAS supports produced rather worse results.
Thus I jumped into the water and packaged OpenBLAS 0.3.5 (the version current Scipy wheels are built against), largely copying from the [MacPorts package](https://github.com/macports/macports-ports/blob/master/math/OpenBLAS/Portfile).
The commits here build for Python versions 2.7-3.7 and pass all tests except …

Scipy update to 1.2.1 and Python 3.7 built against new OpenBLAS package

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pycodestyle-py.info

Fixes test failure in testsuite.test_all.PycodestyleTestCase for py >= 36.

pycodestyle 2.5.0

---

10.9-libcxx/stable/main/finkinfo/database/postgresql10.info
10.9-libcxx/stable/main/finkinfo/database/postgresql94.info
10.9-libcxx/stable/main/finkinfo/database/postgresql95.info
10.9-libcxx/stable/main/finkinfo/database/postgresql96.info

latest updates for postgresql packages:
- postgresql10 update to 10.8
- postgresql96 update to 9.6.13
- postgresql95 update to 9.5.17
- postgresql94 update to 9.4.22

postgresql updates May 19

---

10.9-libcxx/stable/main/finkinfo/sci/netcdf-c15.info

Upstream update to version 4.7.0.
Also updated license, as changed upstream.
Removed unnecessary BuildDepends: doxygen
Moved CPPFLAGS and LDFLAGS from ConfigureParams to SetCPPFLAGS and SetLDFLAGS.
Successfully built and tested with "fink build -m" on Mac OS 10.14.5 with Command Line Tools 10.2.1

netcdf-c15-4.7.0-1: Upstream update

---

10.9-libcxx/stable/main/finkinfo/database/postgresql10.info
10.9-libcxx/stable/main/finkinfo/database/postgresql11.info
10.9-libcxx/stable/main/finkinfo/database/postgresql94.info
10.9-libcxx/stable/main/finkinfo/database/postgresql95.info
10.9-libcxx/stable/main/finkinfo/database/postgresql96.info

postgresql upstream updates  11.4 10.9 9.6.14 9.5.18 9.4.23.
Upstream updates includes security fix for CVE-2019-10164

postgresql upstream updates June 2019

---

10.9-libcxx/stable/main/finkinfo/sci/nco.info

This is the result of an upstream update from version 4.7.9 to 4.8.1.
The addition of the `export PERL5LIB` is necessary as the package looks for `Locale/Messages.pm`, which is only available in the directory `%p/lib/perl5/5.18.2`
If there is a way to avoid hardcoding that path, please let me know.
Successfully built with `fink -m build` on Mac OS 10.14.5 with Command Line Tools 10.2

nco-4.8.1-1: upstream update

---

10.9-libcxx/stable/main/finkinfo/sci/eccodes.info
10.9-libcxx/stable/main/finkinfo/sci/eccodes.patch

Also removed dependency on libjasper and libjpeg. Jasper support is deprecated by eccodes, and libopenjpeg is sufficient.
Compiled and tested successfully on 10.14.5 with Command Line Tools 10.2.1

eccodes-2.13.0-1: Upstream update and adjustment of dependencies

---

10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-pkgmaker-r-0.22.info

cran-pkgmaker-r version 0.27 uses a R-3.2 function (isNamespaceLoaded), and thus cran-pkgmaker-r31 is not buildable.

Remove -r31 variant from pkgmaker; Add -r31 variant at a lower version

---

10.9-libcxx/stable/main/finkinfo/sci/eccodes.info

Simple upstream update.
Built and tested with `fink -m build` on Mac OS 10.14.6 with Command Line Tools 10.3

eccodes-2.13.1: upstream update

---

10.9-libcxx/stable/main/finkinfo/sci/cdo.info

Simple upstream update to `cdo` and `cdo-openmp`.
Compiled and tested successfully with "fink -m build" on Mac OS 10.14.6 with Command Line Tools 10.3

cdo-1.9.7.1: upstream update

---

10.9-libcxx/stable/main/finkinfo/database/postgresql10.info
10.9-libcxx/stable/main/finkinfo/database/postgresql11.info
10.9-libcxx/stable/main/finkinfo/database/postgresql94.info
10.9-libcxx/stable/main/finkinfo/database/postgresql95.info
10.9-libcxx/stable/main/finkinfo/database/postgresql96.info

postgresql upstream updates 11.5 10.10 9.6.15 9.5.19 9.4.24
Upstream updates includes two security fixes:  
- CVE-2019-10208 (PG 9.4 - 11) 
- CVE-2019-10209 (PG 11)

postgresql upstream updates August 2019

---

10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-biobase-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-biocgenerics-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-graph-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-impute-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-iranges-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-limma-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-massspecwavelet-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-multtest-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-pcamethods-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-preprocesscore-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-protgenerics-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-qvalue-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-rgraphviz-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-s4vectors-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-siggenes-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-sspa-r.info

Simply updated the bioconductor modules to the latest versions of the upstream.

New upstream versions based on bioconductor 3.6

---

10.9-libcxx/stable/main/finkinfo/database/redis.info
10.9-libcxx/stable/main/finkinfo/database/redis.patch

Update redis to latest upstream version 5.0.5.
Compile against jemalloc to solve failed tests.
@krbullock please check the package as the package maintainer or let me know if I should takeover the maintainer role.

New upstream version redis 5.0.5

---

10.9-libcxx/stable/main/finkinfo/base/bzip2.info
10.9-libcxx/stable/main/finkinfo/base/gzip.info
10.9-libcxx/stable/main/finkinfo/base/libiconv.info
10.9-libcxx/stable/main/finkinfo/base/libiconv.patch
10.9-libcxx/stable/main/finkinfo/base/tar.info
10.9-libcxx/stable/main/finkinfo/base/unzip.info

Update libiconv and gzip to the latest upstream.
tar also has a newer 1.32 version, but 3 tests failed, so I didn't touch it.
Also updated some other base packages to use a CustomMirror so that it'll search both upstream and our SF space.

Update some base packages

---

10.9-libcxx/stable/main/finkinfo/sci/netcdf-fortran7.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-fortran8.info

This upstream version of netcdf-fortran is said to require netcdf-c >= 4.6.0, whereas for netcdf-fortran-4.4.5 it was >= 4.6.2. The latter was actually not reflected in the package info file, so that is updated here as well.
In addition, Conflicts/Replaces pairs are added between netcdf-fortran7 and netcdf-fortran8.
Note that this package should have been netcdf-fortran_7_ (it contains libnetcdff._7_.dylib) but the previous package was already _incorrectly_ called netcdf-fortran_7_.
Build and tested with `fink -m build` on Mac OS 10.14.6 with Command Line Tools 10.3.
Note: I purposely did not update netcdf-c to the current version 4.7.1 at this time as there is a significant bug in it that fails testing; thus awaiting 4.7.2. Also an upstream update of netcdf-cxx4 is expected soon.

netcdf-fortran8-4.5.1-1: new package needed due to upstream update

---

10.9-libcxx/stable/main/finkinfo/crypto/gnutls-2.12-shlibs.info
10.9-libcxx/stable/main/finkinfo/crypto/gnutls30-shlibs.info

New gnutls-3.6.10 that needs a new libN=gnutls30.
Also make the old gnutls-2.12 package an shlibs-only stub because nothing else is using it and no sense in carrying it forward.

Gnutls30 update

---

10.9-libcxx/stable/main/finkinfo/sci/gracegtk.info
10.9-libcxx/stable/main/finkinfo/sci/gracegtk.patch
10.9-libcxx/stable/main/finkinfo/sci/qrupdate.info
10.9-libcxx/stable/main/finkinfo/sci/qrupdate.patch

gracegtk is one of the last remaining packages to use gcc6 (#482) and is the only user of lapack360, which is a gcc5 user (#481). Here's an update to gcc9 and to lapack380 (which will need to migrate to gcc9, but may as well only have to bring the latest lapackXXX moving forward). There's a newer version upstream, but it requires a newer gtk stack than fink has at the moment.

Gracegtk and qrupdate updates: gcc and lapack

---

10.9-libcxx/stable/main/finkinfo/sci/gmt.info
10.9-libcxx/stable/main/finkinfo/sci/gmt6.info

This is a new branch of the GMT package, thus introducing a new package gmt6.
Built and tested with 'fink -m build' on MacOS 10.15.1 with Command Line Tools 11.0.
Also updated the Conflicts/Replaces lines of packages gmt and gmt5.

gmt-6.0.0-1: Introducing GMT 6.0.0

---

10.9-libcxx/stable/main/finkinfo/devel/openmpi.info
10.9-libcxx/stable/main/finkinfo/sci/cdo.info
10.9-libcxx/stable/main/finkinfo/sci/eccodes.info
10.9-libcxx/stable/main/finkinfo/sci/fftw3.info
10.9-libcxx/stable/main/finkinfo/sci/grib-api-fortran.info
10.9-libcxx/stable/main/finkinfo/sci/lapack380.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-fortran8.info
10.9-libcxx/stable/main/finkinfo/sci/wip.info

This updates the following packages to gcc9.
Tested on MacOS 10.15.1 with Command Line Tools 11.2

Move to gcc9

---

10.9-libcxx/stable/main/finkinfo/libs/perlmods/image-exiftool-pm.info

A simple update to the latest upstream version, 11.75. Tested on 10.14.6.

image-exiftool-pm new upstream version 11.75

---

10.9-libcxx/stable/main/finkinfo/sci/xtide-harmonics-us.info
10.9-libcxx/stable/main/finkinfo/sci/xtide.info

New upstream version of xtide (2.15.2) and US harmonics files (20190620).
Maintainer is @akhansen

xtide upstream version 2.15.2 and harmonics 20190620

---

10.9-libcxx/stable/main/finkinfo/database/postgresql10.info
10.9-libcxx/stable/main/finkinfo/database/postgresql11.info
10.9-libcxx/stable/main/finkinfo/database/postgresql94.info
10.9-libcxx/stable/main/finkinfo/database/postgresql95.info
10.9-libcxx/stable/main/finkinfo/database/postgresql96.info

PR contains:
- postgresql upstream updates 11.6 10.11 9.6.16 9.5.20 9.4.25
- preparation for next major release  PostgreSQL 12
PostgreSQL 9.4 (postgresql94) goes EOL on February 2020 and PostgreSQL 9.5 (postgresql95) a year later (EOL Feb. 2021), so we should also start for this releases a migration tracker?

PostgreSQL upstream updates November 2019

---

10.9-libcxx/stable/main/finkinfo/crypto/nettle7-shlibs.info

The Debian patchfile in the existing infofile doesn't exist on the server any more, preventing this package from building. The updated patchfile appears to work as expected. As I can't download the old patchfile, I'm not sure what has changed.
Maintainer is @nieder

nettle7-shlibs 3.5.1 - updated Debian patchfile

---

10.9-libcxx/stable/main/finkinfo/libs/libarchive31.info
10.9-libcxx/stable/main/finkinfo/libs/libarchive31.patch

An update to the latest upstream version 3.4.0. Tested on 10.14.5 and 10.15.
The previous update was made by @nieder in 2016, noting a "maintainer timeout".

libarchive (and bsdtar) upstream version 3.4.0

---

10.9-libcxx/stable/main/finkinfo/games/fortune-mod.info
10.9-libcxx/stable/main/finkinfo/games/fortune-mod.patch
10.9-libcxx/stable/main/finkinfo/libs/rinutils.info

Changes:
- new version with new upstream repository
- uses recode3 instead of recode
- uses cmake
- uses "rinutils" headers (which have been added as a separate package in libs as part of this PR)
Tested on 10.15.2, including with "-m"

fortune-mod: new upstream version

---

10.9-libcxx/stable/main/finkinfo/sci/openblas.info
10.9-libcxx/stable/main/finkinfo/sci/openblas.patch

Part of the gcc8 migration #489. Added some fine tuning of the optimisation options and a few benchmark runs as part of the `TestScript`. Tested on 10.12.6.

OpenBLAS migrated to gcc9 and update to upstream 0.3.7

---

10.9-libcxx/stable/main/finkinfo/sci/pandas-py-0.19.2.info
10.9-libcxx/stable/main/finkinfo/sci/pandas-py.info

Update to pandas-py 0.25.3
Only works with python35 and up, so copy the existing old version .info for older pythons.
Many tests fail or error out with missing data files that are in Git but not in the tarball, so I disabled tests (which were already disabled in our older version).

pandas-py 0.25.3

---

10.9-libcxx/stable/main/finkinfo/editors/ess.info

The updated `emacs26` package (thanks!) is not in the dependency options of `ess`. This version adds the new emacsen and is updated to the latest upstream, with the emacsen-common install voodoo now pulled separately from Debian. Tested on 10.12.6.

ESS update to 18.10.2 + emacs26 compatibility

---

10.9-libcxx/stable/main/finkinfo/sound/mp3diags.info

Switch to openssl110 (though doesn't seem to be used anyway. maybe obsolete IBD?) and misc other dep cleanups.

mp3diags: dep updates

---

10.9-libcxx/stable/main/finkinfo/libs/libserf0-openssl110.patch
10.9-libcxx/stable/main/finkinfo/libs/libserf0.info

Upstream added openssl110 support in 1.3.8->1.3.9, which does not apply cleanly to this very old version (we have 1.3.9 in libserf1). Here, just backport the minimal changes to buckets/ssl_buckets.c to enable clean compiling.

libserf0: update to openssl110

---

10.9-libcxx/stable/main/finkinfo/sci/atlas-xcode7.patch
10.9-libcxx/stable/main/finkinfo/sci/atlas.info

Update atlas to latest stable 3.10.3.
Also bumps internal LAPACK. There are newer LAPACK releases, but 3.6.1 was the latest available when 3.10.3 was released, so most likely to not introduce any issues.

Atlas 3.10.3

---

10.9-libcxx/stable/main/finkinfo/sci/cernlib2006.info
10.9-libcxx/stable/main/finkinfo/sci/geant4.9.info
10.9-libcxx/stable/main/finkinfo/sci/patchy4.info
10.9-libcxx/stable/main/finkinfo/sci/root-pythia.info
10.9-libcxx/stable/main/finkinfo/sci/root5.info
10.9-libcxx/stable/main/finkinfo/sci/root5.patch
10.9-libcxx/stable/main/finkinfo/sci/xrootd4.info

Migrates @mommsen packages to gcc9
* root5 moves to the latest (from 2018) of the 5x release series and was made available through 10.13 where I could test. Not clear why it was previously kept out of 10.12+.
* geant4.9 is not at the last of the 4.9 series (that's 4.9.6p4) but I didn't try to increase the Fink version.
This corresponds to #481 and #489

migrate mommsen packages to gcc9

---

10.9-libcxx/stable/main/finkinfo/sci/cernlib2006.info

xmkmf is available for distribution 10.14.5, which allows building cernlib on this platform, too.

Add 10.14.5 to available distributions

---

10.9-libcxx/stable/main/finkinfo/games/sdl2-image.info
10.9-libcxx/stable/main/finkinfo/games/sdl2-mixer.info
10.9-libcxx/stable/main/finkinfo/games/sdl2-ttf.info

SDL2 versions of sdl-image, sdl-mixer, and sdl-ttf. Based on the current SDL1 packages.
I can take them over if desired.

SDL2 versions of sdl-image, sdl-mixer, and sdl-ttf

---

10.9-libcxx/stable/main/finkinfo/database/postgresql10.info
10.9-libcxx/stable/main/finkinfo/database/postgresql11.info
10.9-libcxx/stable/main/finkinfo/database/postgresql12.info
10.9-libcxx/stable/main/finkinfo/database/postgresql94.info
10.9-libcxx/stable/main/finkinfo/database/postgresql95.info
10.9-libcxx/stable/main/finkinfo/database/postgresql96.info

PR contains:
PostgreSQL upstream updates 12.2 11.7 10.12 9.6.17 9.5.21 9.4.26.  The upstream updates fixes the security issue CVE-2020-1720.
This is the last update for the PostgreSQL 9.4 , which is now EOL.

PostgreSQL upstream updates February 2020

---

10.9-libcxx/stable/main/finkinfo/devel/libtool2.info

help2man is needed to rebuild doc/libtool.1

Add missing dependency on help2man

---

10.9-libcxx/stable/main/finkinfo/languages/perl5162-timelocal-y2020.patch
10.9-libcxx/stable/main/finkinfo/languages/perl5162.info
10.9-libcxx/stable/main/finkinfo/languages/perl5182-timelocal-y2020.patch
10.9-libcxx/stable/main/finkinfo/languages/perl5182.info
10.9-libcxx/stable/main/finkinfo/languages/perl5184-timelocal-y2020.patch
10.9-libcxx/stable/main/finkinfo/languages/perl5184.info
10.9-libcxx/stable/main/finkinfo/text/texi2html-perl5162-timelocal-y2020.patch
10.9-libcxx/stable/main/finkinfo/text/texi2html-perl5162.info

Closes #579
Tested on 10.13 and 10.15 for relevant perl51X packages

Fix assumptions from internal time::local about 2-digit years.

---

10.9-libcxx/stable/main/finkinfo/sci/openblas.info
10.9-libcxx/stable/main/finkinfo/sci/openblas.patch

Updated the `openblas` package to latest upstream and worked around a failure on compilation of the `smallscaling` benchmark program on OS X 10.11 (and presumably earlier) due to missing `CLOCK_MONOTONIC` reported [here](https://sourceforge.net/p/fink/mailman/message/36927850).
Also modified the `-mtune` option - see discussion in `DescPackaging`, as the `intel` option did not seem to enable all optimisations for the latest CPUs supported with gcc9 - might see some performance improvement on the latest iMac Pro or Mac Pro.

OpenBLAS updated to 0.3.8 and fixed smallscaling build on 10.11 and lower

---

10.9-libcxx/stable/main/finkinfo/editors/exuberant-ctags.info
10.9-libcxx/stable/main/finkinfo/editors/exuberant-ctags_unused_namespace.patch

Fix exuberant-ctags build on 10.14 with __unused macro issues.

---

10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-prettyunits-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-testthat-r-2.2.1.info

CRAN testthat and prettyunits depend on each other, causing a circular dependency conflict.
testthat:
Added 
DEP: cran-prettyunits-r%type_pkg[rversion] (>= 1.1.1-2),
CONFLICTS: cran-prettyunits-r%type_pkg[rversion] (= 1.1.1-1)
prettyunits:
Removed the dependencies (which were only "suggested").

Fix circular dependencies

---

10.9-libcxx/stable/main/finkinfo/devel/lazarus-doc.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-carbon.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-cocoa-32bit.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-cocoa.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-gtk2.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-qt4.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-qt5.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-win32.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-win64.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-wince-arm.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-wince-i386.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus.info

lazarus: update to new upstream version (2.0.8). No further change.

lazarus: update to new upstream version (2.0.8)

---

10.9-libcxx/stable/main/finkinfo/languages/python27.info
10.9-libcxx/stable/main/finkinfo/languages/python27.patch
10.9-libcxx/stable/main/finkinfo/languages/python34.info
10.9-libcxx/stable/main/finkinfo/languages/python34.patch
10.9-libcxx/stable/main/finkinfo/languages/python35.info
10.9-libcxx/stable/main/finkinfo/languages/python35.patch
10.9-libcxx/stable/main/finkinfo/languages/python36.info
10.9-libcxx/stable/main/finkinfo/languages/python36.patch
10.9-libcxx/stable/main/finkinfo/languages/python37.info
10.9-libcxx/stable/main/finkinfo/languages/python37.patch

don't compare numbers as strings
Closes #598 
Only python27 was updated to the latest upstream, which is the last python27 ever. python36-38 were left at their current older versions since it was more critical to get the patch in (latest branch versions still have this problem).
For some reason, python38 doesn't FTBFS with Xcode11.4 even though the relevant detection code is the same AFAICT.

proper detection of clang-v11 from Xcode 11.4 (python)

---

10.9-libcxx/stable/main/finkinfo/crypto/gnutls30-shlibs.info
10.9-libcxx/stable/main/finkinfo/crypto/gnutls30-xcode11.4.patch

Fix build failure with Xcode11.4
Fix test failure from code that expects (but forgets to check for) not-yet-released version of nettle library.

GnuTLS 3.6.13

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pysvn-py.info

pysvn 1.9.10 fails to build against `svn19` 1.13. I've bumped the version to latest upstream, tested to build both against `svn19-dev` 1.12.1 and 1.13.0, and also added a `py38` variant.
https://pysvn.sourceforge.io/downloads.html only states support for Python 3.5 upwards, but the `py34` variant built without any obvious problems (again with both `svn19` versions).

Update pysvn to 1.9.11 for svn19 1.13 compatibility and add py38 variant

---

10.9-libcxx/stable/main/finkinfo/languages/ruby24.info
10.9-libcxx/stable/main/finkinfo/languages/ruby24.patch
10.9-libcxx/stable/main/finkinfo/languages/ruby25.info
10.9-libcxx/stable/main/finkinfo/languages/ruby26.info

Updates for the ruby packages that are still maintained upstream. Simple %v bumps. ruby24 has a little extra change added one test that consistently failed w/out that change. With the change, that test consistently passes on my system.
Tested on 10.13/Xcode10.1

Ruby updates

---

10.9-libcxx/stable/main/finkinfo/crypto/gnutls30-shlibs.info

This builds on #599. If xcode isn't installed, but the command-line tools are, the patch still won't be applied correctly. This small change should fix that. Since nothing is changed with the compilation, the revision has not been bumped.

Fix GnuTLS 3.6.13 build when xcode isn't installed

---

10.9-libcxx/stable/main/finkinfo/sci/openblas.info
10.9-libcxx/stable/main/finkinfo/sci/openblas.patch

On the beginners mailing list this build failure for version 0.3.8 was reported https://sourceforge.net/p/fink/mailman/message/37022781/
due to the CPU version not being detected on the build system. The update includes fixes for auto-detecting a range of newer hardware like https://github.com/xianyi/OpenBLAS/commit/303bdb6 so hopefully may address this. Also switched to gcc10 for the build; tested with numpy-py38.

Update openblas to upstream 0.3.9 and gcc10

---

10.9-libcxx/stable/main/finkinfo/languages/python27.info
10.9-libcxx/stable/main/finkinfo/languages/python27.patch
10.9-libcxx/stable/main/finkinfo/languages/python34.info
10.9-libcxx/stable/main/finkinfo/languages/python35.info
10.9-libcxx/stable/main/finkinfo/languages/python36.info
10.9-libcxx/stable/main/finkinfo/languages/python37.info
10.9-libcxx/stable/main/finkinfo/languages/python38.info
10.9-libcxx/stable/main/finkinfo/languages/python38.patch

When checking the newer Python 3.x packages, I noticed that the tests are all failing immediately because `install_name_tool` is called on a non-existent `python.exe`.
Changed that to the default executable name and updated to the latest upstream.
3.7.6 and 3.8.1 however are failing with one persistent failure in `test_startup_imports`.
Also fixed #530; tested on 10.12.

ENH: Python3 updates and test suite fixes

---

10.9-libcxx/stable/main/finkinfo/libs/id3lib4.info
10.9-libcxx/stable/main/finkinfo/libs/id3lib4.patch

On 10.15, id3lib4 fails with this error:
```
/bin/sh ../libtool --mode=link g++  -g -O2 -Wall -Wno-unused -Wno-inline -Woverloaded-virtual -Wmissing-declarations    -o libid3.la -rpath /opt/sw/lib -version-info 3:0:0 -export-dynamic c_wrapper.lo field.lo field_binary.lo field_integer.lo field_string_ascii.lo field_string_unicode.lo frame.lo frame_impl.lo frame_parse.lo frame_render.lo globals.lo header.lo header_frame.lo header_tag.lo helpers.lo io.lo io_decorators.lo io_helpers.lo misc_support.lo mp3_parse.lo readers.lo spec.lo tag.lo tag_file.lo tag_find.lo tag_impl.lo tag_parse.lo tag_parse_lyrics3.lo tag_parse_musicmatch.lo tag_parse_v1.lo tag_render.lo utils.lo writers.lo  -L/opt/sw/lib -lz -liconv
mkdir .libs
rm -fr .libs/libid3.la .libs/libid3.* .libs/libid3.*
*** Warning: This …
```

Fix build failure linking id3lib library on 10.15 by modernizing autotools components

---

10.9-libcxx/stable/main/finkinfo/languages/pyqt5-mac-py.info

Fixes the issues with #567
* Remove old inherited OpenSSL dep
* Add f-p-p to help track deps
* clean up deps to fit what's actually being used by the package

build cleanup for PyQt5

---

10.9-libcxx/stable/main/finkinfo/devel/scons2.info
10.9-libcxx/stable/main/finkinfo/libs/libserf1.info

in #637 libserf1 can't build with scons-3.0.5 due to old code in env.SharedLibrary. This adds back a legacy scons2-v2.1.5 package that conflicts/replaces with current scons and allows libserf1 to build. This closes #637

Add legacy scons2 package to deal with libserf1 FTBFS

---

10.9-libcxx/stable/main/finkinfo/net/librtmp1-shlibs.info
10.9-libcxx/stable/main/finkinfo/net/librtmp1-shlibs.patch
10.9-libcxx/stable/main/finkinfo/net/rtmpdump.info

Updates rtmpdump to v2.4, which is a new libN=1.
v2.4 still doesn't build with openssl110, but has the option to use gnutls instead.
Also, they no longer provide tarballs after v2.3, so I made a snapshot tarball at the last commit in March 30, 2019.
I've successfully built ffmpeg and gst-plugins-bad against the new librtmp1. Libcurl4 is the only other package that uses the old librtmp-v2.3 package.

Rtmpdump update to v2.4

---

10.9-libcxx/stable/main/finkinfo/sci/openblas.info
10.9-libcxx/stable/main/finkinfo/sci/openblas.patch

New upstream version with two additional changes:
1. I got another report on a build failure of the entire benchmark suite on 10.11 due to missing CLOCK_REALTIME etc. support in `time.h`; judging from [this comment](https://github.com/Tarsnap/tarsnap/issues/286#issuecomment-331666331) this is systemic to Xcode 8 and earlier. Trying to work around here with `mach/clock_types.h` definitions, but yet to be tested on 10.11.
EDIT: The failure occurs for 6 of the benchmarks that have been newly added or changed to use `clock_gettime`; see comment for resolution.
2. Switched the benchmark build to dynamically linked binaries, since the `*.goto` executables were growing well beyond 1 GB in total. No obvious performance differences to the statically linked versions.

OpenBLAS update to 0.3.10 and new fix for missing CLOCK_REALTIME

---

10.9-libcxx/stable/main/finkinfo/devel/fink-package-precedence.info
10.9-libcxx/stable/main/finkinfo/devel/fink-package-precedence.patch

currently, f-p-p tests for the command line tools' `otool-classic` before falling back to `/usr/bin/otool`. f-p-p should also check for Xcode's `otool-classic` before giving up.
Tested with libidn2.0-shlibs as per #613 
Fixes #616

f-p-p: search for Xcode's otool-classic before falling back to /usr/bin/otool

---

10.9-libcxx/stable/main/finkinfo/database/postgresql10.info
10.9-libcxx/stable/main/finkinfo/database/postgresql11.info
10.9-libcxx/stable/main/finkinfo/database/postgresql12.info
10.9-libcxx/stable/main/finkinfo/database/postgresql96.info

PR contains:
PostgreSQL upstream updates 12.4 11.9 10.14  9.6.19 to fix security issues
CVE-2020-14349 and  CVE-2020-14350 .

PostgreSQL upstream updates August 2020

---

10.9-libcxx/stable/main/finkinfo/devel/gperf.info

New version of the stand-alone to sync with 52b6737 update to libiconv's onboard version.

new gperf version 3.1

---

10.9-libcxx/stable/main/finkinfo/libs/perlmods/extutils-makemaker-pm-10.11.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/extutils-makemaker-pm-10.12.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/extutils-makemaker-pm-10.13.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/extutils-makemaker-pm-10.14.5.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/extutils-makemaker-pm-10.14.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/extutils-makemaker-pm-10.15.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/extutils-makemaker-pm-10.9.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/extutils-makemaker-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/extutils-makemaker-pm.patch

Fix #461 by patching EU::MM to use absolute paths for INST_ARCHLIB so that system-perl on 10.15 is happy loading bundles.

Fix extutils-makemaker-pm to deal with hardened system-perl on 10.15

---

10.9-libcxx/stable/main/finkinfo/devel/ninja.info

Suggested update after 3½ years and seeing comments in a dependent package (#582) about performance improvements for versions >= 1.9.
The test setup seems to have changed, no longer needing a `gtest` but rather the build option using `cmake`. For some reason this also creates a 3x larger executable than the `./configure.py` build, but I could not identify differences in functionality between the two. Therefore still installing the latter and just using the former for the test suite. Comments welcome if we should rather switch to a pure cmake build.

ninja update to 1.10.0 with tests

---

10.9-libcxx/stable/main/finkinfo/sound/libgsm1-shlibs.info

`libgsm1-shlibs` fails validation on an `install_name` pointing to `%b`.
For some reason the Makefile is installing everything in mode 444; leaving `libgsm.1.dylib` owner-writable as is custom for about all other dylibs.

Fix libgsm.1.dylib install name

---

10.9-libcxx/stable/main/finkinfo/libs/slang2.info

Using i_n_t on the SONAME symlink causes the actual library to be rebuilt with the original install_name during `make check`, which then fails.
Use i_n_t on the physical file to avoid the rebuild.

Fix slang2 testing on 11.0

---

10.9-libcxx/stable/main/finkinfo/libs/json-c.info
10.9-libcxx/stable/main/finkinfo/libs/json-c5.info

New version of json-c, with a library main version bump...
Tested on 10.15.7 with xcode 12.2. Compiles and tests with "-m".
If this is accepted, it might be worth bumping the version in gdal2 (#697).

json-c5: version 0.15

---

10.9-libcxx/stable/main/finkinfo/sci/mbsystem.info

Bumped to latest libproj19. Compiles with "-m" and appears to work correctly.

mbsystem: bump to proj19

---

10.9-libcxx/stable/main/finkinfo/devel/cmake.info

New upstream version of cmake. Same patches as before. Updated source URL to Github, and website URL to https. Compiles with "-m" using xcode 12.3 on 10.15.7 and appears to work correctly. Maintainer is @costabel.

cmake 3.19.1 - new upstream

---

10.9-libcxx/stable/main/finkinfo/graphics/libgeotiff2.info

update to libgeotiff2 v1.4.3
This is the last release for the libN=2 series. Latest v1.6.0 is libN=5
Tested to build on 10.13 and 10.15/Xcode12.2

Libgeotiff2 update

---

10.9-libcxx/stable/main/finkinfo/sci/libtcd.info
10.9-libcxx/stable/main/finkinfo/sci/xtide-coastline.info
10.9-libcxx/stable/main/finkinfo/sci/xtide-harmonics-us.info
10.9-libcxx/stable/main/finkinfo/sci/xtide.info

Trivial updates to xtide packages. Latest upstream (minor) versions, tarballs changed from .bz2 to .xz (requiring a BuildDepend for fink >= 0.32).
Maintainer is @akhansen.

xtide 2.15.3, libtcd 2.2.7-r3, xtide-harmonics-us 20191229

---

10.9-libcxx/stable/main/finkinfo/sci/xephem.info
10.9-libcxx/stable/main/finkinfo/sci/xephem.patch

Upstream package has not seen any real updates in 5 years but is still working fine, however some of the online sources for background star catalogues, minor planets and comets ephemerides have moved and/or changed formats.
The initial motivation for the fix was the failure to load background stars from the HST Guide Star Catalogue 2.4 (enabled in the `Field stars` menu, which is still successfully accessed, but could not be parsed due to a change in no. and order of columns. The download test was also trying to access R band magnitudes, which are missing for almost all stars in GSC, making the setup fail. I have replaced them with the IR J magnitude; this is only used as a last fallback option for a stellar magnitude.
Also updated default URLs for some other sites, but reading them in …

XEphem fixes for Guide Star Catalogue and other downloads

---

10.9-libcxx/stable/main/finkinfo/devel/git-lfs.info
10.9-libcxx/stable/main/finkinfo/devel/git-lfs.patch

Added patch to remove the use of git which was failing to retrieve the version number correctly, and `@!` which was causing gnumake v4.2.1 (as installed by fink) to fail to build.

Building git-lfs using fink gnumake 4.2.1

---

10.9-libcxx/stable/main/finkinfo/sci/clipper.info
10.9-libcxx/stable/main/finkinfo/sci/coot.info
10.9-libcxx/stable/main/finkinfo/sci/libccp4.info
10.9-libcxx/stable/main/finkinfo/sci/phaser-mpi.info
10.9-libcxx/stable/main/finkinfo/sci/refmac.info
10.9-libcxx/stable/main/finkinfo/sci/refmac.patch
10.9-libcxx/stable/main/finkinfo/sci/tinker.info
10.9-libcxx/stable/main/finkinfo/sci/usf.info

This is for #481 to close down gcc5.
There are upstream bumps for some packages (coot, mmdb2, libccp4), but I didn't follow them.

migrate wgscott packages to gcc9

---

10.9-libcxx/stable/main/finkinfo/sci/libnc-dap3.info
10.9-libcxx/stable/main/finkinfo/sci/libnc-dap3.patch

* -I ordering (put local before external/global
* resolve implicit-declaration warnings
* fix printf string security

libnc-dap3: gcc upgrade, resolve some warnings, etc

---

10.9-libcxx/stable/main/finkinfo/net/libcurl4.info

Fixes a bunch of CVEs, and also in support of Issue #650

libcurl4: new version, librtmp upgrade

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/asn1crypto-py.info

Install failed because of a lower-case `readme.md`; also forwarded to latest upstream version.

Fixed asn1crypto DocFiles for case-sensitive FS, update to 1.4

---

10.9-libcxx/stable/main/finkinfo/sci/udunits2.info

Updated the UDUNITS2 package to the latest upstream version. Only major change is to use GCC 9 as the compiler, so it plays nice with Fortran (I could not get this to compile with Xcode 12 otherwise).
Tested on 10.15.7 with xcode command line tools 12.2. Compiles and passes tests with "-m".
Maintainer is @akhansen.

udunits2 2.2.28 - new upstream

---

10.9-libcxx/stable/main/finkinfo/graphics/ilmbase24-shlibs.info
10.9-libcxx/stable/main/finkinfo/graphics/ilmbase24-shlibs.patch
10.9-libcxx/stable/main/finkinfo/graphics/libopenexr24-shlibs.info
10.9-libcxx/stable/main/finkinfo/graphics/libopenexr24-shlibs.patch

Bug fixes for OpenEXR and IlmBase 2.4.2: the pkgconfig files omitted the prefix from the include/library paths...
Maintainer is @nieder

libopenexr24 and ilmbase24 - fix pkgconfig files

---

10.9-libcxx/stable/main/finkinfo/database/libspatialite2-shlibs.info
10.9-libcxx/stable/main/finkinfo/database/libspatialite2.info
10.9-libcxx/stable/main/finkinfo/database/libspatialite5-shlibs.info
10.9-libcxx/stable/main/finkinfo/database/libspatialite5-shlibs.patch
10.9-libcxx/stable/main/finkinfo/database/spatialite-gui.info
10.9-libcxx/stable/main/finkinfo/database/spatialite-gui.patch

This set of commits cleans up the builds of libspatialite2 and libspatialite5, converts the remaining users of 5 to use the latest (7), and fixes a bunch of build flaws along the way. With 2 and 5 both no longer used, they are converted to only their -shlibs package.

Spatialite update

---

10.9-libcxx/stable/main/finkinfo/libs/libe-book01-dev.info
10.9-libcxx/stable/main/finkinfo/libs/libepubgen0.info
10.9-libcxx/stable/main/finkinfo/libs/librvngabw0.info

Bump packages using cppunit1.12.1 to cppunit1.15.1.  cppunit1.12.1 doesn't build on Big Sur.
After this, `libetonyek` is the only package left using the old cppunit1.12.1, and that's failing tests with either version of cppunit. There's newer `libetonyek`, but it requires an upgrade to a new libN of `mdds`.

Cppunit upgrade

---

10.9-libcxx/stable/main/finkinfo/languages/python37.info
10.9-libcxx/stable/main/finkinfo/languages/python37.patch

Python37 wasn't building for me on 10.15.7: once it reached the stage where the modules were being compiled, setup.py was moving the system headers ahead of Fink's, causing compilation of the sqlite3 and readline modules to fail.
This fix comments out three offending lines in setup.py. It's been tested on 10.15.7, but should probably also be tested on 11.0 to ensure it doesn't break #682

python37 - fix build on 10.15

---

10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-affy-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-affyio-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-annotate-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-biobase-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-biocgenerics-r-0.28.0.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-biocgenerics-r-0.34.0.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-biocparallel-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-graph-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-impute-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-kegggraph-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-limma-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-massspecwavelet-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-multtest-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-mzid-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-mzr-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-pcamethods-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-preprocesscore-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-protgenerics-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-qvalue-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-rgraphviz-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-rhdf5lib-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-siggenes-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-sspa-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/bioconductor-vsn-r.info

New upstream versions for bioconductor packages. Biocgenerics has a newer version for r >= 4.0.  Fink packages have not yet privided packages for R >= 4.0.  Some packages depend on Biocgenerics (>=0.27.1) so versioned .info files are added.

Bioconductor 20201211

---

10.9-libcxx/stable/main/finkinfo/graphics/libvips42-shlibs.info
10.9-libcxx/stable/main/finkinfo/graphics/nip2.info
10.9-libcxx/stable/main/finkinfo/kde/kstars4.info
10.9-libcxx/stable/main/finkinfo/libs/octmods/fits-oct.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/astropy-py.info

From static cfitsio to shared libcfitsio8-dev/-shlibs. Along the way, overhaul libvips42's .pc to stop leaking dependencies on internal-use-only libs.
Pinging @nieder (libvips/nip2), @akhansen (fits-oct), @dhomeier (astropy)
There are a few other reverse-dependencies on old cfitsio, but they will involve more substantial updates.

Cfitsio upgrade

---

10.9-libcxx/stable/main/finkinfo/text/mupdf.info
10.9-libcxx/stable/main/finkinfo/text/mupdf.patch

New upstream version of mupdf, which no longer uses openssl

new version: mupdf

---

10.9-libcxx/stable/main/finkinfo/database/postgis.info
10.9-libcxx/stable/main/finkinfo/libs/gdal3.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/gdal-py.info
10.9-libcxx/stable/main/finkinfo/sci/gmt-shlibs.info
10.9-libcxx/stable/main/finkinfo/sci/gmt5-shlibs.info
10.9-libcxx/stable/main/finkinfo/sci/gmt6-shlibs.info
10.9-libcxx/stable/main/finkinfo/sci/mbsystem.info

Here is a new package for gdal version 3.2.0. This PR depends on #712 (for changes to gdal2) and #718 (for bug fixes in openexr24 pkgconfig files, which otherwise break compilation).
gdal-py now includes an extensive suite of tests (for gdal itself and gdal-py)! I've tested these with 2.7 and 3.7. There is one test in the transformations where a slightly larger error margin is required; and two places where there are known issues with MacOS that needed a slight tweak in the test scripts. And one script with a unicode character that causes an error with 2.7 (but not with later versions). In addition, the pytest version needs to be specified in the makefile if more than one type is installed. With these small caveats (four tests out of thousands), the library appears to work correctly and …

Gdal3 - and a few updates to packages that depend on it

---

10.9-libcxx/stable/main/finkinfo/libs/perlmods/b-keywords-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/b-keywords-pm.patch

Needs hackery for a self-test to find system-perl's headers.

new b-keywords-pm version

---

10.9-libcxx/stable/main/finkinfo/languages/setuptools-tng-py.info
10.9-libcxx/stable/main/finkinfo/languages/setuptools-tng-py27.info
10.9-libcxx/stable/main/finkinfo/languages/setuptools-tng-py34.info

Update setuptools to the latest upstream (including separate last versions for py27 and py34).
Still can't enable tests because of circular dependencies on pytest (and a couple missing modules we don't have).
Tested using the new setuptools-tng-py37 on several pymods

Setuptools-py update to 47.3.1

---

10.9-libcxx/stable/main/finkinfo/net/nmap.info

Newer nmap is required to run on Big Sur.

nmap: New upstream.

---

10.9-libcxx/stable/main/finkinfo/database/postgresql10.info
10.9-libcxx/stable/main/finkinfo/database/postgresql11.info
10.9-libcxx/stable/main/finkinfo/database/postgresql12.info
10.9-libcxx/stable/main/finkinfo/database/postgresql94-implicit-declarations.patch
10.9-libcxx/stable/main/finkinfo/database/postgresql94.info
10.9-libcxx/stable/main/finkinfo/database/postgresql95-implicit-declarations.patch
10.9-libcxx/stable/main/finkinfo/database/postgresql95.info
10.9-libcxx/stable/main/finkinfo/database/postgresql96-implicit-declarations.patch
10.9-libcxx/stable/main/finkinfo/database/postgresql96.info

@wodev 
Updates for postgresql packages
For postgresql9X, had to patch configure to successfully build when using Xcode12 and it's implicit-declaration enforcements.
For postgresql1X, simple version bumps that contain a fix for a test in earlier releases that failed when not in daylight savings time.

Postgresql updates

---

10.9-libcxx/stable/main/finkinfo/graphics/mplayer.info
10.9-libcxx/stable/main/finkinfo/kde/kdebase4-runtime.info
10.9-libcxx/stable/main/finkinfo/kde/libkf5js5-shlibs.info
10.9-libcxx/stable/main/finkinfo/kde/libkf5wallet5-shlibs.info
10.9-libcxx/stable/main/finkinfo/kde/libktorrent5-shlibs.info

Bump deps on libgcrypt and gnutls to their latest libversions.
There are large trees of packages with deps on older gpgme lib, not sure if it's a problem to update them piecemeal, so I did not touch here (or check to see if the ton of BDep without accompanying Dep are even needed). Also not touching boost deps for similar reason.

Nieder upgrades (security-related deps)

---

10.9-libcxx/stable/main/finkinfo/sci/root5.info
10.9-libcxx/stable/main/finkinfo/sci/root5.patch

Especially important here is a switch to using external libxxhash/lv4 (fink package dep), to avoid build-time
downloading of sources.

root5: Dep upgrades

---

10.9-libcxx/stable/main/finkinfo/net/librtmp1-shlibs.info
10.9-libcxx/stable/main/finkinfo/net/librtmp1-shlibs.patch

Trying to address:
* [Fink-users] problem compiling librtmp1-shlibs-2.4-20190330-2
* [Fink-users] "librtmp1: library not found for -lgnutls" 10.14.6, xcode 10.3
These changes might not solve it, but should make it fail harder sooner rather than deferring until after the original failure began to occur.

Misc librtmp build-fixes

---

10.9-libcxx/stable/main/finkinfo/graphics/libjpeg8-turbo.info

Update to 1.5.3
This is the last version that uses autotools.
Current upstream is 2.0.6 which is cmake based

Jpeg8 turbo update

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/cppy-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/kiwisolver-py.info

I found that the kiwisolver 1.2.0 build fails if pip is not installed, and that it pip-installs a dependency `cppy` during the build phase, if it is. I think this goes against packaging rules, so I have added that package as `BuildDepends` (I checked that the tests are still running successfully after cppy has been removed).
Updated to the latest upstream along the way and also removed a patch to the tests that no longer seems required.

New package cppy-py as build dependency for kiwisolver; update to upstream 1.3.1

---

10.9-libcxx/stable/main/finkinfo/languages/lua53.info

- change from http to https
- add missing doc/index.css

lua53: update to upstream version 5.3.6

---

10.9-libcxx/stable/main/finkinfo/devel/aarch64-binutils.info
10.9-libcxx/stable/main/finkinfo/devel/arm-binutils.info
10.9-libcxx/stable/main/finkinfo/devel/binutils-docs.info
10.9-libcxx/stable/main/finkinfo/devel/i386-binutils.info
10.9-libcxx/stable/main/finkinfo/devel/m68k-binutils.info
10.9-libcxx/stable/main/finkinfo/devel/mipsel-binutils.info
10.9-libcxx/stable/main/finkinfo/devel/powerpc-binutils.info
10.9-libcxx/stable/main/finkinfo/devel/powerpc64-binutils.info
10.9-libcxx/stable/main/finkinfo/devel/riscv32-binutils.info
10.9-libcxx/stable/main/finkinfo/devel/riscv64-binutils.info
10.9-libcxx/stable/main/finkinfo/devel/sparc-binutils.info
10.9-libcxx/stable/main/finkinfo/devel/sparc64-binutils.info
10.9-libcxx/stable/main/finkinfo/devel/x86-64-binutils-default.info
10.9-libcxx/stable/main/finkinfo/devel/xtensa-binutils.info

Adding binutils for xtensa, risc32, and risc64.

binutils: update to upstream version 2.36.1

---

10.9-libcxx/stable/main/finkinfo/devel/flex-devel.info

New upstream version, added the PDF manual to the docs – this does increase the installed size by about 1 MB.
On a related issue, does anyone recall details about the compatibility problems of the newer version vs. the standard 2.5.4a package? I.e. is Fink stuck with defaulting to a quarter-century old (alpha?) version that no longer has an original source location? There is a "final" version 2.5.39 of the 2.5 branch, but as `flex-devel` originally seems to have branched off with 2.5.35, I presume any issues that version had would be present in 2.5.39 as well... There are also some older versions on https://github.com/westes/flex/releases (but not quite as old as 2.5.4), but it's unclear whether these are alpha, beta or gamma versions, and none of them even has a working `configure` …

flex-devel update to 2.6.4 and PDF doc build

---

10.9-libcxx/stable/main/finkinfo/libs/caca-doxygen.patch
10.9-libcxx/stable/main/finkinfo/libs/caca.info
10.9-libcxx/stable/main/finkinfo/libs/hermes.info
10.9-libcxx/stable/main/finkinfo/libs/libmediainfo0.info
10.9-libcxx/stable/main/finkinfo/libs/libzen0.info

Two things here:
- Rooting out the last packages specifically requiring automake1.14.
- Other upgrades to the libmediainfo0 build process.

automake bumps and libtinyxml2 compensation

---

10.9-libcxx/stable/main/finkinfo/libs/perlmods/compress-raw-bzip2-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/compress-raw-lzma-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/compress-raw-zlib-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/io-compress-lzf-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/io-compress-lzma-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/io-compress-lzop-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/io-compress-pm.info

update to various compress perlmods
Bump to latest upstreams
Add pm5184 and pm5282 as needed
io-compress-lzf had a note about newer releases failing tests, but I tested on 10.14.6 and all tests passed for all perl variants.

io-compress update

---

10.9-libcxx/stable/main/finkinfo/sci/xtide-harmonics-us.info
10.9-libcxx/stable/main/finkinfo/sci/xtide.info

A trivial update to xtide: use the latest data files (released in January). Maintainer is @akhansen

xtide: use latest harmonic data files

---

10.9-libcxx/stable/main/finkinfo/sci/cernlib2006.info

So disable header-tracking and avoid linking against a lib that isn't directly used anyway.

cernlib2006: fix FTBFS: no bin/makedepend or libXp.dylib in xquartz-2.8.0

---

10.9-libcxx/stable/main/finkinfo/sci/grace-implicit-declarations.patch
10.9-libcxx/stable/main/finkinfo/sci/grace.info

Fix implicit declaration errors during configure
bump to netcdf-c18 because -c7 deps on hdf5.10, which doesn't build with Xcode12 (more implicit declarations).

grace: updates for Xcode12

---

10.9-libcxx/stable/main/finkinfo/sci/r-base33.info
10.9-libcxx/stable/main/finkinfo/sci/r-base34.info
10.9-libcxx/stable/main/finkinfo/sci/r-base35.info
10.9-libcxx/stable/main/finkinfo/sci/r-base36-implicit-declarations.patch
10.9-libcxx/stable/main/finkinfo/sci/r-base36.info

* Add libxt as an explicit dep to avoid using libxt-flat.
* Add upstream patch to fix implicit warning errors during the detection of Accelerate.framework on 10.15. Otherwise, package tries to build libRblas.dylib.
* Restrict r-base[3-5] through Dist=10.14.5 to match what we're already doing for the rmods.

build fixes and cleanup for r-base3[3-6]

---

10.9-libcxx/stable/main/finkinfo/languages/perl5302-libperl-t.patch
10.9-libcxx/stable/main/finkinfo/languages/perl5302-macos11.patch
10.9-libcxx/stable/main/finkinfo/languages/perl5302-timehires.patch
10.9-libcxx/stable/main/finkinfo/languages/perl5302.info
10.9-libcxx/stable/main/finkinfo/languages/perl5302.patch

Tested on 10.14.6 and passes all tests. 
dist/Time-HiRes/t/stat occasionally fails like this:
```
dist/Time-HiRes/t/stat ......................................... #   Failed test at t/stat.t line 35.
FAILED at test 27
```
but it is not reproducible.
I've temporarily lost access to my VMs, so please check with other systems, especially macOS 10.12 and macOS11.0/1/2.

New pkg perl5302 to match system-perl on 11.3

---

10.9-libcxx/stable/main/finkinfo/devel/pasdoc-gui.info
10.9-libcxx/stable/main/finkinfo/devel/pasdoc.info

pasdoc-gui: use lazarus-cocoa and the included script to create the app-bundle.

pasdoc: update to upstream version 0.16.0

---

10.9-libcxx/stable/main/finkinfo/base/expat1.info

To fix DNS vulnerability [CVE-2013-0340](https://marc.info/?l=oss-security&m=136580776324285&w=2,) as reported in #831 updates (incrementally) to the upstream versions 2.4.0/2.4.1.
Build otherwise unchanged (except for switch to tar.xz source), passes both tests on Mojave 18.7.0.

Update expat1 to fix Billion Laughs vulnerability

---

10.9-libcxx/stable/main/finkinfo/languages/icon.info
10.9-libcxx/stable/main/finkinfo/languages/icon.patch

The .so is built flat installed in bin/ as in previous versions; I
have no idea how this file might get used so I don't know if the
location and/or binary library flags are correct.

icon: new version, switch to 64-bit arch

---

10.9-libcxx/stable/main/finkinfo/libs/libaudiofile1.info

update to latest libaudiofile (from 2013).
Adds Ubuntu's patches which contain several fixes for CVEs

libaudiofile 0.3.6

---

10.9-libcxx/stable/main/finkinfo/libs/libzip2.info
10.9-libcxx/stable/main/finkinfo/libs/libzip5.info

Main functional change is that the userland binaries package (zimcmp, zipmerge, ziptool) is now not lib-versioned and uses ">=" not "=" on -shlibs (avoids several deadlock situations). Is "libzip-bin" the best name (was libzipN-bin), or should it instead be "zip-bin" or "zip"? Debian has a separate package for each of the three binaries, which seems excessive to me.

Libzip overhaul

---

10.9-libcxx/stable/main/finkinfo/utils/e2fsprogs.info
10.9-libcxx/stable/main/finkinfo/utils/e2fsprogs.patch

Here is the latest upstream version of e2fsprogs. Changes include:
- Added `#include <time.h>` to `lib/blkid/probe.c` (fixes implicit declaration error)
- Added the testsuite to the info-file
- Name of license file changed from COPYING to NOTICE
- Library compatibility versions remain the same, so no changes required there.
Builds on 10.15.7, also with `-m`, and all tests pass. Sorry, I haven't upgraded to Big Sur yet... Maintainer is @TheSin-

e2fsprogs: update to 1.46.2, add testsuite

---

10.9-libcxx/stable/main/finkinfo/languages/python310.info
10.9-libcxx/stable/main/finkinfo/languages/python310.patch
10.9-libcxx/stable/main/finkinfo/languages/python37-macos11.patch
10.9-libcxx/stable/main/finkinfo/languages/python37.info
10.9-libcxx/stable/main/finkinfo/languages/python38.info
10.9-libcxx/stable/main/finkinfo/languages/python39.info
10.9-libcxx/stable/main/finkinfo/languages/python39.patch

Adds new packages python39 and python310.
Python-3.9 is the first upstream to directly support macOS 11 and macOS 12.
We haven't been able to get python38 and earlier to work on  macOS 11/12, so this is the first python that builds and runs on these systems. Latest python-3.8.12 *might* support macOS11/12, but not sure yet.
I removed a lot of the OS-versioned hacks (mostly around finding the SDK and system library cache) that had accumulated into the earlier pythons to work with newer macOS because the underlying issues had been taken care of upstream.
Also cleaned up the lists of tests to just those that currently are known to fail (on macOS12).
Tested on just macOS 12.1.
Please test on anything before 10.14.5.

New packages python39 and python310

---

10.9-libcxx/stable/main/finkinfo/sci/r-base31.info
10.9-libcxx/stable/main/finkinfo/sci/r-base32.info
10.9-libcxx/stable/main/finkinfo/sci/r-base33.info
10.9-libcxx/stable/main/finkinfo/sci/r-base35.info
10.9-libcxx/stable/main/finkinfo/sci/r-base36.info
10.9-libcxx/stable/main/finkinfo/sci/r-base40.info
10.9-libcxx/stable/main/finkinfo/sci/r-base40.patch
10.9-libcxx/stable/main/finkinfo/sci/r-base41.info
10.9-libcxx/stable/main/finkinfo/sci/r-base41.patch

r-base40 and r-base41 are added.
Dependency updated from readline6 and readline7 to readline8.
There is a LAPACK-related error during the test process for r-base40. This seems a known bug. r-base41's corresponding test has been disabled.
https://stat.ethz.ch/pipermail/r-help/2020-May/467080.html

Add r-base40, r-base41; Use readline8

---

10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-rjava-r.info

This version works well. There is a newer version of rJava for R >= 3.6, though.

cran-rjava-r: stable version for older R

---

10.9-libcxx/stable/main/finkinfo/sci/openblas.info
10.9-libcxx/stable/main/finkinfo/sci/openblas.patch

Current upstream release; tested to build with gcc11 on 10.13 and 10.14 – don't know if it needs to be versioned for others.

Update openblas to 0.3.19 and build with gcc11

---

10.9-libcxx/stable/main/finkinfo/crypto/openssl110-dev.info
10.9-libcxx/stable/main/finkinfo/crypto/openssl300-dev.info

a PullRequest to fix issue #888 which causes start issue of PostgreSQL on macOS 10.12 with OpenSSL 1.1.1l/1.1.1m or OpenSSL 3.0.

OpenSSL -  disable apple  crypto random api on macOS 10.12 and lower 

---

10.9-libcxx/stable/main/finkinfo/database/postgresql12.info
10.9-libcxx/stable/main/finkinfo/database/postgresql12.patch

updates the PostgreSQL 12 package to the latest upstream package and change the dependency for OpenSSL to OpenSSL 3.0.

postgresql12 new upstream 12.10

---

10.9-libcxx/stable/main/finkinfo/sci/qhull8.0-shlibs.info

Upstream still supports libqhull even though it now also has libqhull_r, and the API changes mean it's not always trivial to migrate existing users of the older interface. Also flip libqhullcpp to shared (both changes per Debian patches).
This allows eventual killing of qhull6.3.1.

qhull8.0: revive non-reentrant lib, unified in existing -shlibs/-dev

---

10.9-libcxx/stable/main/finkinfo/sci/xtide-harmonics-us.info
10.9-libcxx/stable/main/finkinfo/sci/xtide.info

A very simple update: a handful of bug fixes in the main code, and updated harmonics files.
Tested on MacOS 10.15.7, where it builds and appears to work correctly. Maintainer is @akhansen

xtide: bump to version 2.15.4 with harmonics 20220109

---

10.9-libcxx/stable/main/finkinfo/sci/arpack-ng.info
10.9-libcxx/stable/main/finkinfo/sci/octave-10.13-3.8.2.info
10.9-libcxx/stable/main/finkinfo/sci/octave-10.14-3.8.2.info
10.9-libcxx/stable/main/finkinfo/sci/octave-10.14.5-3.8.2.info
10.9-libcxx/stable/main/finkinfo/sci/octave-3.8.2.info
10.9-libcxx/stable/main/finkinfo/sci/qrupdate.info

Incl. matching arpack-ng and qrupdate flavours.
Built and tested for the 10.14.5 distribution; gcc11+openblas also with 10.13.
I had an earlier version of this working with gcc9 on 10.12, but cannot test that right now.
I have also built the base (`[-blas] = .`) variant, but _not_ the atlas version in  a while!

octave-3.8.2 gcc11 + lapack3 upgrade and openblas

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/future-py.info
10.9-libcxx/stable/main/finkinfo/sci/uncertainties-py.info

Update to current upstream, fixing the `nosetests` call for #917.
This version requires `future-py`, which comes in with the missing pyversions as well; also trying to get its tests to run again. As far as I could check, the enabled tests are running without network access now.
Tested all variants on 10.14.5, py39/310 on 12.4 and 10.13.6 as well.

Uncertainties 3.1.6

---

10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-checkmate-r-2.0.0.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-checkmate-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-cli-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-cluster-r-2.1.2.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-cluster-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-dt-r-0.20.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-gam-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-httpuv-r-1.6.1.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-httpuv-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-knitr-r-1.37.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-magrittr-r-2.0.2.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-maxlik-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-mockery-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-mstate-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-nlme-r-3.1-155.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-nlme-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-nmf-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-processx-r-3.5.2.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-processx-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-prospectr-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-ps-r-1.6.0.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-ps-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-rio-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-usethis-r-2.0.1.info

This is primarily a regular updates, most of which are not available for older Rs.
The existing cran-httpuv-r was found unbuildable for R 3.5 and earlier. So, httpuv 1.6.1 is back for such versions.

New upstream versions for CRAN with some fixes

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/bootstrap-modules-py-build_env.patch
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/bootstrap-modules-py-flit_core-timestamps.patch
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/bootstrap-modules-py-install-__init__.py.patch
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/bootstrap-modules-py-installer_scripts.patch
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/bootstrap-modules-py-pep517-no-deps-option.patch
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/bootstrap-modules-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/build-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pep517-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/tomli-py.info

Python is trying to get rid of setuptools with new backends and frontends for building pymods (PEP517). Not exactly sure what all that means. But many packages will start not including setup.py anymore.
This creates a bootstrap module that contains several of the necessary packages for building these new PEP517 packages. Because many depend on each other, they're installed all as one Fink package as pure python (and stashed in %p/share).
Other packages that need them can just add to PYTHONPATH as necessary in order to build.

Pep517 build system

---

10.9-libcxx/stable/main/finkinfo/sci/mbsystem.info

A trivial update to mbsystem:
- update to latest release version (5.7.8)
- update the perl and python versions in the info file
Tested on Mac OS 12.6.1 (using @TheSin-'s dpkg1.16 branch), where it appears to work, including with "-m" (using Python 3.10 for the tests).

mbsystem 5.7.8

---

10.9-libcxx/stable/main/finkinfo/crypto/gnupg2.info

Fixes a typo in the source checksum in @nieder's latest commit!

gnupg2: 2.2.40 - typo in checksum

---

10.9-libcxx/stable/main/finkinfo/devel/help2man-perl.info
10.9-libcxx/stable/main/finkinfo/devel/intltool40-13.0.info
10.9-libcxx/stable/main/finkinfo/devel/po4a-13.0.info
10.9-libcxx/stable/main/finkinfo/devel/xmkmf-12.0.info
10.9-libcxx/stable/main/finkinfo/devel/xmkmf-13.0.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/capture-tiny-pm-13.0.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/math-matrixreal-pm-13.0.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/module-build-pm-13.0.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/package-generator-pm-13.0.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/test-simple-pm-13.0.info

Mostly perlmods for `system-perl5303` without further changes required; tested on arm64 as well.
The `xmkmf`-distversions from 10.14 to 13.0 are really identical, wondering if we really need separate package files for all.

Distribution: 13.0 versions of various packages

---

10.9-libcxx/stable/main/finkinfo/devel/ninja.info

Fixes #932 (tested on 12.1-13.1 – no further py3 conversion needed).

Enable python3 for ninja bootstrap on macOS 11+

---

10.9-libcxx/stable/main/finkinfo/graphics/aquaterm-1.1.1-5.info
10.9-libcxx/stable/main/finkinfo/graphics/aquaterm-1.1.1-5.patch
10.9-libcxx/stable/main/finkinfo/graphics/aquaterm.info
10.9-libcxx/stable/main/finkinfo/graphics/aquaterm.patch

The old revision had `MACOSX_DEPLOYMENT_TARGET=10.7`, and 10.5 in the xcodeproj. Set here to the minimum accepted by Xcode 14 on 13.2, which still builds as is with Xcode 11.3.1 on 10.14.6, but obviously will need to dist-restrict this for still older versions – or set the target depending on the build host?

AquaTerm build update to Xcode 14

---

10.9-libcxx/stable/main/finkinfo/sci/xtide-harmonics-us.info
10.9-libcxx/stable/main/finkinfo/sci/xtide.info

Updated packages for xtide (v. 2.15.5) and xtide-harmonics-us (v. 20230107) to the latest upstream versions. These are trivial updates, and appear to work correctly on MacOS 12.6.3 / Intel.
Package maintainer is @akhansen

xtide update

---

10.9-libcxx/stable/main/finkinfo/libs/boost1.53..info
10.9-libcxx/stable/main/finkinfo/libs/boost1.55.info
10.9-libcxx/stable/main/finkinfo/libs/boost1.58.info
10.9-libcxx/stable/main/finkinfo/libs/boost1.63.info
10.9-libcxx/stable/main/finkinfo/libs/boost1.68.info
10.9-libcxx/stable/main/finkinfo/libs/boost1.78.info

As part of a sweep to upgrade as many packages as possible to the latest libicuXX libversion, this is my quick pass at the boost* package sets.
I did not investigate further what caused the non-detection in the oldest boost libversions (1.53 and 1.55). But one clue is I'm fairly sure that libicu as of 6x-ish requires c++11, so older boost might not be using that. Given those boost are already dist-restricted and not used, probably not worth any time thinking more about it. We'll just have to dist-restrict (rather than kill off altogether) the libicu55 headers package in the future.

Boost icu upgrade

---

10.9-libcxx/stable/main/finkinfo/text/miktex-tools.info
10.9-libcxx/stable/main/finkinfo/text/miktex-tools.patch

Bump miktex-tools to the latest release.
The jpeg typedef fix is no longer needed because the file is gone.
Still not OpenSSL3 friendly.
Asking @dmacks because he recently tested/updated our current .info

Miktex tools update

---

10.9-libcxx/stable/main/finkinfo/graphics/frei0r-dev.info

Resolve some FTBFS:
* The new version changed the opencv detection recipe.
* pkgconfig(cairo) entails a few other packages even though their specific .h are not accessed at compile-time.

frei0r: dependency fixes

---

10.9-libcxx/stable/main/finkinfo/libs/openldap24.info
10.9-libcxx/stable/main/finkinfo/libs/openldap26-xcode12.patch
10.9-libcxx/stable/main/finkinfo/libs/openldap26.info
10.9-libcxx/stable/main/finkinfo/libs/openldap26.patch

Creates a new package for openldap-2.6
* The server and executables are in openldap26, which C/R older openldap24. I have no idea if we can just normalize to an openldap2 package.
* The library now uses a normal versioning scheme, and the new library package is openldap2-shlibs/-dev, which C/R the older openldap24-dev.

Openldap 2.6 update

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/packaging-py-20.9.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/packaging-py.info

@dhomeier update for packaging-py, which is the latest upstream.
This only supports py37+ now, so I pushed off the earlier version to a new .info file.
The new release no longer uses setuptools but requires the boostrap-modules-py package.
Tested on 10.14.6 with py37-py310. I need this update for hatchling-py, which is a new backend for packages that use the pep517 system, that I need for an apipkg-py update that I need for another pkg that I need for...
Also tested hatchling-py and a couple other pymods that use packaging-py and they all still build/pass.

packaging-py: v23.1

---

10.9-libcxx/stable/main/finkinfo/sci/fftw3.info
10.9-libcxx/stable/main/finkinfo/sci/fftw3.patch

First, a bug fix: 
- rather than invoking Apple's preprocessor directly, preprocess via GCC (by calling "gcc-fsf-11 -E"). If we don't do this, we end up with a bunch of errors when checking header usability.
- Also, header paths are CPPFLAGS, not CFLAGS.
And then we add support for Apple silicon:
- an upstream patch for using the Arm `CNTVCT_EL0` counter on Apple silicon (FFTW/fftw3#267)
- remove the Intel-specific command-line arguments when compiling on Apple silicon
- specify support for the `CNTVCT_EL0` counter. Strictly speaking, this probably isn't necessary, as the first patch should enable this support automatically on MacOS. Alternatively, we could specify this argument and omit the patchfile. Probably comes under the heading of "belt and braces"...
This all requires a working …

fftw3 - add support for Apple silicon and fix preprocessor

---

10.9-libcxx/stable/main/finkinfo/sci/gmt6-shlibs.info
10.9-libcxx/stable/main/finkinfo/sci/gmt6-shlibs.patch

A quick patch to allow GMT6 to build on Apple Silicon - from GenericMappingTools/gmt#4584. Depends on #1042 to have fftw3 working on Apple Silicon.

gmt6: fix for Apple Silicon

---

10.9-libcxx/stable/main/finkinfo/devel/ddd.info
10.9-libcxx/stable/main/finkinfo/editors/nedit.info
10.9-libcxx/stable/main/finkinfo/sci/afni.info
10.9-libcxx/stable/main/finkinfo/sci/cernlib2006.info
10.9-libcxx/stable/main/finkinfo/sci/dx.info
10.9-libcxx/stable/main/finkinfo/sci/geant4.9.info
10.9-libcxx/stable/main/finkinfo/sci/geomview195-shlibs.info
10.9-libcxx/stable/main/finkinfo/sci/grace.info
10.9-libcxx/stable/main/finkinfo/sci/mbsystem.info
10.9-libcxx/stable/main/finkinfo/sci/molmol.info
10.9-libcxx/stable/main/finkinfo/sci/orrery.info
10.9-libcxx/stable/main/finkinfo/sci/xephem.info
10.9-libcxx/stable/main/finkinfo/sci/xmakemol.info
10.9-libcxx/stable/main/finkinfo/text/texlive.info
10.9-libcxx/stable/main/finkinfo/text/xpdf.info
10.9-libcxx/stable/main/finkinfo/x11/mesa-libglw.info
10.9-libcxx/stable/main/finkinfo/x11/openmotif4-2level-implicit_declaration.patch
10.9-libcxx/stable/main/finkinfo/x11/openmotif4-2level.info
10.9-libcxx/stable/main/finkinfo/x11/openmotif4-2level.patch
10.9-libcxx/stable/main/finkinfo/x11/xbae.info

Based on @PovlAbrahamsen work on #1003 , this moves all packages using openmotif4-2.3.4 and libxt-flat to openmotif4-2.3.8 and two_level libxt.
Openmotif4 couldn't just be updated in place because some packages built against flat libxt/openmotif would fail if then running against the two_level libraries.
So I made a new package `openmotif4-2level` for v2.3.8 linking to libxt, that puts the libraries into a hidden directory so they can coexist with the older `openmotif4` v2.3.4 linking to libxt-flat. The dev and bin packages go straight into %p and C/R with the older openmotif4.
This PR is all packages and 1 library using libxt-flat, now transitioned to the new openmotif4-2level and libxt.

transition openmotif4 to two_level libxt

---

10.9-libcxx/stable/main/finkinfo/languages/swi-prolog-7.2.3.info
10.9-libcxx/stable/main/finkinfo/languages/swi-prolog-7.2.3.patch
10.9-libcxx/stable/main/finkinfo/languages/swi-prolog.info
10.9-libcxx/stable/main/finkinfo/languages/swi-prolog.patch

This is the latest upstream version. Our previous version was pinned on openssl100 (Issue #499), whereas this is openssl300.
There is a shared library, whose install_name has changed, so whereas the previous package has a swi-prolog-{shlibs,dev}, this one has swi-prolog9-{shlibs,dev} instead. By policy, we would keep at least the old -shlibs, so I retainined the old swi-prolog.info at a different .info filename. There's a packaging note about 'ppl' using it, but our ppl package does not (and I can't find that it ever has in our current distro). So I have no objection to nuking the old version altogether to clear an openssl100 dependant altogether. Anyone have any objections?

swi-prolog: new version

---

10.9-libcxx/stable/main/finkinfo/web/lighttpd.info
10.9-libcxx/stable/main/finkinfo/web/lighttpd.patch

lighttpd: update to lighttpd 1.4.71
lighttpd 1.4.25 was released in Nov 2009, over 13 years ago!!!
There are a number of important security and bug fixes that are missing in fink lighttpd.info, besides many improvements.  
Modern lighttpd releases are (generally) still portable to run on very old systems.  The current version of lighttpd is also available for Macs in https://github.com/macports/macports-ports, under https://github.com/macports/macports-ports/tree/master/www/lighttpd
lighttpd release notes over the years announce deprecation and migration paths of some modules which may have been in lighttpd 1.4.25, but are no longer in current lighttpd releases.
mod_cml -> mod_magnet
mod_compress -> mod_deflate
mod_geoip -> mod_maxminddb
lighttpd mod_magnet works with any version of lua …

lighttpd: update to lighttpd 1.4.71

---

10.9-libcxx/stable/main/finkinfo/editors/joe.info
10.9-libcxx/stable/main/finkinfo/editors/ldapvi.info
10.9-libcxx/stable/main/finkinfo/libs/lz4.info
10.9-libcxx/stable/main/finkinfo/libs/lzo2.info
10.9-libcxx/stable/main/finkinfo/net/socat.info
10.9-libcxx/stable/main/finkinfo/web/lynx-cur.info
10.9-libcxx/stable/main/finkinfo/web/netrik.info
10.9-libcxx/stable/main/finkinfo/web/nginx.info

Remove read_only_stubs flag
This flag causes problems in Xcode 15 which does not seem to pass it correctly to ld.
gripped read_only_stubs from packages.  Two other packages have it commented out.

Remove read_only_stubs flag

---

10.9-libcxx/stable/main/finkinfo/sci/nco.info
10.9-libcxx/stable/main/finkinfo/sci/ncview.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-c19.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-cxx4.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-fortran8.info

New upstream versions of NetCDF:
- NetCDF-C version 4.9.2 bumps library version to 19. Existing packages already have conflicts set up for netcdf-c19.
- NetCDF-Fortran8 version 4.6.1: use gcc 12, library compatibility version increased.
- NetCDF-CXX4: use new C library; having a file called "VERSION" conflicts with system headers, so we have to make sure that configure doesn't create this file (which doesn't appear to be used anyway)...
- NCO: new upstream version 5.1.8; use new NetCDF library
- ncview: use new NetCDF library
These have been built on MacOS 13.6 on x86_64 with "-m", and appear to work correctly.

netcdf updates

---

10.9-libcxx/stable/main/finkinfo/sci/emboss-6.5.7.info
10.9-libcxx/stable/main/finkinfo/sci/emboss-6.6.0.info
10.9-libcxx/stable/main/finkinfo/sci/libplplot18-5.15.0-shlibs.info
10.9-libcxx/stable/main/finkinfo/sci/saga-haru.patch
10.9-libcxx/stable/main/finkinfo/sci/saga.info
10.9-libcxx/stable/main/finkinfo/text/libharu2.2.1-shlibs.info
10.9-libcxx/stable/main/finkinfo/text/libharu2.3.0-shlibs.info
10.9-libcxx/stable/main/finkinfo/text/libharu2.4-shlibs.info
10.9-libcxx/stable/main/finkinfo/text/libharu2.4-shlibs.patch

Update to latest upstream, migrate all reverse-depends  to the latest libversion, and convert older now-unused older libversions to -shlibs-only stubs.

Libharu new libversion

---

10.9-libcxx/stable/main/finkinfo/sci/openblas.info
10.9-libcxx/stable/main/finkinfo/sci/openblas.patch

Latest upstream version; adding an additional replacement for `CLOCK_*` functions missing from 10.11 or earlier – thanks to David Neuhaus for reporting this.
Optimisation options also add a check for M1 (aarch64), for now as `arm` until an Architecture is officially set.

OpenBLAS update to 0.3.20 and test/benchmark fix for pre-10.12

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/bleach-py-3.1.0.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/bleach-py-6.0.0.info

Updates bleach-py to the latest upstreams. The package itself has been loosely deprecated by upstream, but we might as well have the latest versions. There's a new similar binding called `nh3`, but it requires `ammonia`, which requires rust.

Bleach py update

---

10.9-libcxx/stable/main/finkinfo/devel/logilab-common-py.info

Simple change again just adding python 3.9 and 3.10 to package.

Update python versions for logilab-common to include 3.9 and 3.10

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/lazy-object-proxy-py.info

Simple update to lazy-object-proxy to allow astroid-py310 to build.  Hopefully this is the last dependancy for pylint update.
Have added this PR as a depends for pull request #1139
Did not update version of lazy-object-proxy since was pointed out that needs updated setuptools which will take extensive testing.

Update lazy-object-proxy for python 3.9 and 3.10

---

10.9-libcxx/stable/main/finkinfo/devel/astroid-py.info

Simple addition of 3.9 and 3.10 to python versions for astroid.  I have a package that I haven't pushed an update for years but have a bunch of these updates in my local tree.

Update astroid info for python versions 3.9 and 3.10

---

10.9-libcxx/stable/main/finkinfo/devel/pylint-py.info

Added python 3.9 and 3.10 to the info file as options

Update pylint for python 3.9 and 3.10

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/oauthlib-py.info

Just added to available python versions 3.9 and 3.10

Oauthlib updated to Python 3.9 and 3.10

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/requests-oauthlib-py.info

Just added support for python 3.9 and 3.10, working through the dependencies slowly

requests-oauthlib added support for python 3.9 and 3.10

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/monotonic-py.info

Added python 3.9 and 3.10 to the available python versions for monotonic

Updated Monotonic to include Python 3.9 and 3.10

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/s3transfer-py.info

New package for the s3transfer python module for automated transfers to S3 repositories.  Builds on 14.5 and 13.6

First release of s3transfer python module package version 0.10.2

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/botocore-py.info

New package botocore for AWS services.  Replacing old boto-py with upstream botocore and boto3.  Test phase commented out due to need for AWS credentials to be installed for testing.  And I think I got the source file correct for once.... :-)

New package botocore for AWS services

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/jmespath-py.info

The jmespath-py package is a required package for boto3-py package (PR #1152)

New package jmespath-py to parse JSON coded text.

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/diskcache-py.info

diskcache-py is needed to test new version of fasteners.  This version will install.
However this will NOT run the tests, since it needs django to be installed, which needs docutils to be installed.  docutils is horribly out of date and  will not build with python 3.10 (or maybe much earlier), the current installed version needs eventlet-py which is very deprecated and will not build for python 3.  I would rather not try to update an infinite number of packages.  And leave docutils-py to a later date and someone more competent.  With diskcache installed, fasteners will pass all tests.  ( see PR #1148 )

diskcache-py initial package

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/mock-py-3.0.5.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/mock-py.info

Update mock to version 5.1.0, rename old version for python < 3.4 with mock current version 3.0.5
mock now supports python 3.10
passes fink -m tests on MacOS 14.5-Sonoma / Xcode 15.4 (command line tools 15.3)
Have emailed maintainer (Charles Lepple) who gave permission to update as I see fit.  Did original update to 3.0.5 to support python 3.10 in 2019.  Updated to 5.1.0 2024.

Mock update to version 5.1.0

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/boto3-py.info

Older boto-py has been split into two utilities.  boto3-py depends on botocore-py ( PR #1151 ).  The boto3-py codes has no testing phase.

boto3-py new package to replace/update boto-py

---

10.9-libcxx/stable/main/finkinfo/crypto/paramiko-py.info
10.9-libcxx/stable/main/finkinfo/crypto/paramiko-py.patch

simple addition of python 3.9 and 3.10
in addition fixed copy of docs files
I believe all dependencies already updated.

paramiko: added supported by python 3.9 and 3.10

---

10.9-libcxx/stable/main/finkinfo/utils/duplicity.info

Upstream bug fix update, also changed pytest to reliably and repeatedly pass all tests.

duplicity - Upstream update to V3.0.2

---

10.9-libcxx/stable/main/finkinfo/devel/help2man-perl.info

Simple update of file, builds and installs on macOS 15.1, shouldn't change anything for other OS and perl versions.

Updated help2man for perl 5.34.1 and macOS 15.0

---

10.9-libcxx/stable/main/finkinfo/gnome/glib2-shlibs.info
10.9-libcxx/stable/main/finkinfo/gnome/glib2-shlibs.patch

Added cast to strcmp function, line 2361 of gdesktopappinfo.c needed (int (*)(const void *, const void *)) before strcmp for consistency.
I applied existing patch file to source, edited gdesktopappinfo.c and created new patch file, but there seem to be more differences between the patch files than the one edit.
(getting closer to building ghostscript)

Update to glib2-shlibs to compile under CLT 16.1 / macOS 15.X

---

10.9-libcxx/stable/main/finkinfo/libs/perlmods/locale-gettext-pm.info

Added perl version 5.34.1 as possible version for system perl in macOS 15.X

Update locale-gettext for MacOS 15 / perl 5.34.1

---

10.9-libcxx/stable/main/finkinfo/web/libtidyp-shlibs.info

Only a small patch to config.guess required, should even continue to support powerpc ;-)
the rest of the build proceeds without further changes.
I was able to build html-tidy-pm in #1181 with this (15.1/Xcode 16.1 arm64).

Support arm processor in libtidyp-shlibs

---

10.9-libcxx/stable/main/finkinfo/net/ncftp.info
10.9-libcxx/stable/main/finkinfo/net/ncftp.patch

patched configure to explicitly define main() to return int, patched in lots of places.    Builds with -m option and package and deb file look good.  Should not change deb package on older systems.

ncftp fix for macOS 15 / Xcode 16.1

---

10.9-libcxx/stable/main/finkinfo/graphics/compface.info
10.9-libcxx/stable/main/finkinfo/graphics/compface.patch

Newer compiler choked on implicit definition.  Now is explicitly "int".  Builds under OS 15.1 and installs.

Update to compface face to patch implicit definition as int

---

10.9-libcxx/stable/main/finkinfo/utils/launch-1.2.5.info
10.9-libcxx/stable/main/finkinfo/utils/launch.info

Launch will not build on newer Xcode that does not support minimum systems back to 10.9.  Updated 
Divided into 2 packages one for compilers with minimum system 10.9 and one for minimum systems 10.13
See Issue #1193
Tested on macOS 10.14.5, 15.2, 14.X

Launch 1.2.5 update

---

10.9-libcxx/stable/main/finkinfo/libs/libopenmpt0-shlibs.info
10.9-libcxx/stable/main/finkinfo/text/asciidoc.info

Simply added 14.4, 15.0 to distribution list.  Packages build and install.
Tested on Sequoia

Package update for Sequoia, packages build on MacOS15/Xcode 16.2

---

10.9-libcxx/stable/main/finkinfo/base/dpkg.info
10.9-libcxx/stable/main/finkinfo/base/gettext-tools-tests.patch
10.9-libcxx/stable/main/finkinfo/base/gettext-tools.info
10.9-libcxx/stable/main/finkinfo/base/libgettext8-shlibs.info
10.9-libcxx/stable/main/finkinfo/base/libgettext8-shlibs.patch
10.9-libcxx/stable/main/finkinfo/base/libiconv.info
10.9-libcxx/stable/main/finkinfo/base/libiconv.patch

Updates libiconv and libgettext/gettext-tools to their latest upstreams. Includes some fixes that are needed for soon to be released macOS15.
Taken from fink/fink#267, which is for bootstrapping, and this is for the installed tree.

update libiconv and gettext to latest upstream for building on macOS15

---

10.9-libcxx/stable/main/finkinfo/web/lighttpd.info
10.9-libcxx/stable/main/finkinfo/web/lighttpd.patch

lighttpd: update to lighttpd 1.4.77

lighttpd: update to lighttpd 1.4.77

---

10.9-libcxx/stable/main/finkinfo/utils/coreutils.info

Seems Clang doesn't treat the attribute as equivalent to the keyword.  Simple one line patch.  This is an upstream patch reference in the info file.  https://savannah.gnu.org/bugs/?63349
Passes maintainer mode referencing that InfoDocs: section is deprecated did not update anything else in the package. Revision bumped to force recompile.  Should be compatible with earlier versions of Clang that do not flag this inconsistency.
(answered own question in Issue #1235)

Coreutils patch for newer Clang

---

10.9-libcxx/stable/main/finkinfo/libs/librsync2.info

Continuation from PR #1222 (librsync) now with clean PR and hopefully fully conformant.
This is version 2.3.4 and installs versioned and unversioned libraries as needed by duplicity and rdiff-backup the only users of librsync.  The original librsync could technically be EOL or discarded.
Not sure what I fixed.  I had this setup already done but did not pass tests.  Now passes maintainer mode tests.

Creation of librsync2 as update to librsync.

---

10.9-libcxx/stable/main/finkinfo/devel/cmake.info

Move cmake to use system-libs where appropriate instead of it's own internal ones.

Cmake system libs

---

10.9-libcxx/stable/main/finkinfo/libs/perlmods/package-generator-pm-15.0.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/term-readkey-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/text-charwidth-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/text-iconv-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/text-wrapi18n-pm.info

Simple updates so that dependencies are satisfied, one new file for distribution 15.0

perlmodule updates for macOS 15 / Perl 5.34.1

---

10.9-libcxx/stable/main/finkinfo/text/gv.info

A revision to gv, to compile against the latest version of libxaw3dxft. I've also cleaned up a few other bits in the info-file, removing a few unnecessary bits (e.g. the calls to pkg-config, which are now called by configure), and adding a dependency to the fontconfig2 and xft2 shlibs (which are linked in the executable).

gv: patch to use latest libxaw3dxft8

---

10.9-libcxx/stable/main/finkinfo/graphics/netpbm11-shlibs.info

I tried building netpbm11-shlibs on Apple Silicon running MacOS 15.6 with Xcode 16.4, and got an error because the compiler had been invoked with SSE options. I have amended the info-file to turn off the SSE options on the command line if we are running on Apple Silicon. I'm not 100% sure whether the revision needs to be bumped here, since it shouldn't actually be changing the underlying compilation.
Maintainer is @nieder

netpbm11-shlibs: fix for compiling on arm64

---

10.9-libcxx/stable/main/finkinfo/libs/gdal3.info
10.9-libcxx/stable/main/finkinfo/libs/gdal3.patch

A change in the `libxml2` headers cause an error with recent versions of clang (fixed in the patchfile).
And at the same time I have bumped dependencies from `libcfitsio8` to `libcfitsio10`, and from `netcdf-c18` to `netcdf-c19`.
Tested on MacOS 15.6, Apple Silicon, Xcode 16.4.

gdal3: fix for recent libxml2, bump dependencies

---

10.9-libcxx/stable/main/finkinfo/libs/libogdi4.info
10.9-libcxx/stable/main/finkinfo/libs/libogdi4.patch

Added libogdi/ogdi#28 to the patchfile to fix building with recent versions of Clang.
Maintainer is @babayoshihiko

libogdi4: fix C99 errors

---

10.9-libcxx/stable/main/finkinfo/database/postgresql12.info
10.9-libcxx/stable/main/finkinfo/database/postgresql12.patch

There are two fixes here:
- A change in the `libxml2` headers cause an error with recent versions of clang (in `src/backend/utils/adt/xml.c`).
- And in recent versions of MacOS, we don't have the required Python headers unless the full Xcode app is installed. So one fix would be to add a build dependency on `xcode.app`. But I've opted to link to Fink's `python310`/`python310-shlibs` instead.
Tested on MacOS 15.6, Apple Silicon, Xcode 16.4. Maintainer is @wodev

postgresql12: fix for recent libxml2, link to Fink's python

---

10.9-libcxx/stable/main/finkinfo/devel/doxygen.info
10.9-libcxx/stable/main/finkinfo/devel/doxygen.patch

Building doxygen failed with MacOS 15.6 and Xcode 16.4, because of missing template argument lists after the template keyword. I have modified the patch to update deps/TinyDeflate/gunzip.hh to the latest version from https://github.com/bisqwit/TinyDeflate - including the fix from #bisqwit/TinyDeflate#9

doxygen: patch for latest clang compiler
