10.9-libcxx/stable/main/finkinfo/crypto/gpgme11.info
10.9-libcxx/stable/main/finkinfo/crypto/libgpgme11-1.9-shlibs.info

Needs new libN due to loss of libgpgme-pthread library.

New libgpgme version 1.9.0.

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/beautifulsoup-py.info

https://sourceforge.net/p/fink/package-submissions/4944/

beautifulsoup-py 4.6.0 from tracker

---

10.9-libcxx/stable/main/finkinfo/languages/ipython-py.info
10.9-libcxx/stable/main/finkinfo/libs/pexpect-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/aniso8601-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/cherrypy-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/cherrypy-py.patch
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/click-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/click-py.patch
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/functools32-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/gsw-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/jinja2-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/jsonschema-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/mako-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/markdown-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/markupsafe-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/mistune-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/mox-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/msgpack-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pickleshare-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pkgconfig-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pluggy-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/ptyprocess-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/terminado-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/tox-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/traitlets-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/versiontools-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/w3lib-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/werkzeug-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/yolk3k-py.info
10.9-libcxx/stable/main/finkinfo/sci/h5py-py.info
10.9-libcxx/stable/main/finkinfo/sci/numexpr-py.info

fixes #23 and several SF submissions.

new python modules and add py36 variants to several others

---

10.9-libcxx/stable/main/finkinfo/graphics/gifsicle.info

gifsicle: update to new upstream version (1.91)

---

10.9-libcxx/stable/main/finkinfo/languages/pascal-p5.info

Subject says it all. At this occasion, many thanks to nieder for his detailed description of the git workflow. Finally, I seem to got it right.

pascal-p5: update to new upstream version (1.4)

---

10.9-libcxx/stable/main/finkinfo/utils/rkhunter.info

Update rkhunter to version 1.4.4

---

10.9-libcxx/stable/main/finkinfo/languages/pascal-p5.info

Thanks to nieder for pointing out the problem with snapshots from sourceforge.

Pascal-P5: Change source to a permanent server.

---

10.9-libcxx/stable/main/finkinfo/sci/pythia8.2.info
10.9-libcxx/stable/main/finkinfo/sci/pythia8.2.patch

Update to latest upstream version.

Update pythia8 to latest version

---

10.9-libcxx/stable/main/finkinfo/net/mutt.info

mutt 1.9.2

---

10.9-libcxx/stable/main/finkinfo/sci/coot.info
10.9-libcxx/stable/main/finkinfo/sci/rdkit.info
10.9-libcxx/stable/main/finkinfo/sci/refmac.info

I hope I have done this correctly.

Coot version update

---

10.9-libcxx/stable/main/finkinfo/utils/clamav.info

New upstream security update. Switch to openssl110.

Update clamav to 0.99.3

---

10.9-libcxx/stable/main/finkinfo/shells/bash.info

Tested on 10.13.3 against Xcode 9.2 using 'fink -m'.

Update bash.info to the 4.4.18 release

---

10.9-libcxx/stable/main/finkinfo/libs/libmpc3.info

Tested on 10.13.3 with Xcode 9.2 using 'fink -m'.

Update libmpc3 to the 1.1.0 release

---

10.9-libcxx/stable/main/finkinfo/crypto/xpwn.info
10.9-libcxx/stable/main/finkinfo/crypto/xpwn.patch

xpwn: headers and linker fixes, openssl110 update

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/python-ldap-py.info

python-ldap-py27 new upstream 2.4.28

---

10.9-libcxx/stable/main/finkinfo/devel/arm-binutils.info
10.9-libcxx/stable/main/finkinfo/devel/i386-binutils.info
10.9-libcxx/stable/main/finkinfo/devel/m68k-binutils.info
10.9-libcxx/stable/main/finkinfo/devel/pasdoc-gui.info
10.9-libcxx/stable/main/finkinfo/devel/pasdoc.info
10.9-libcxx/stable/main/finkinfo/devel/powerpc-binutils.info
10.9-libcxx/stable/main/finkinfo/devel/sparc-binutils.info
10.9-libcxx/stable/main/finkinfo/devel/x86-64-binutils-default.info
10.9-libcxx/stable/main/finkinfo/devel/x86-64-binutils.info

binutils: update to new upstream version (2.30)

---

10.9-libcxx/stable/main/finkinfo/crypto/gsasl9.info
10.9-libcxx/stable/main/finkinfo/crypto/msmtp.info
10.9-libcxx/stable/main/finkinfo/crypto/pidgin.info
10.9-libcxx/stable/main/finkinfo/gnome/midori.info
10.9-libcxx/stable/main/finkinfo/kde/kdepim4-mac.info
10.9-libcxx/stable/main/finkinfo/kde/kopete4.info
10.9-libcxx/stable/main/finkinfo/net/jwhois.info

Notes packages that currently fail to build w/ libidn2 or fail to detect it.
Other maintainers with libidn packages not included here:
@dmacks 
@danielj7 
@gecko2 
@bcully 
@akhansen
Martin Costabel
Dave Reiser
Tomoaki Okayama

Update or note relationship with libidn2

---

10.9-libcxx/stable/main/finkinfo/utils/clamav.info

Update clamav to latest upstream version 0.99.4

New upstream release

---

10.9-libcxx/stable/main/finkinfo/devel/importchecker-py.info
10.9-libcxx/stable/main/finkinfo/editors/bluefish.info
10.9-libcxx/stable/main/finkinfo/graphics/aquaterm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/dbi-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/device-serialport-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/test-numeric-pm.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/beautifulsoup-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/geopy-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pyephem-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/simplejson-py.info
10.9-libcxx/stable/main/finkinfo/sci/convertall.info
10.9-libcxx/stable/main/finkinfo/sci/xephem.info
10.9-libcxx/stable/main/finkinfo/sci/xfoil.info
10.9-libcxx/stable/main/finkinfo/text/aspell.info

no changes except for updated owner email address for multiple packages

update owner email address

---

10.9-libcxx/stable/main/finkinfo/libs/perlmods/image-exiftool-pm.info

update exiftool to latest upstream.  Update maintainer email address

---

10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-carbon.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-cocoa-32bit.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-gtk2.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-qt4.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-qt5.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-win32.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-win64.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-wince-arm.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-wince-i386.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus.info
10.9-libcxx/stable/main/finkinfo/devel/qt5pas.info

Lazarus: Update to new upstrem version (1.8.2).
Lazarus based on Qt5 is new.

Lazarus: Update to new upstrem version (1.8.2)

---

10.9-libcxx/stable/main/finkinfo/database/postgresql96.info

Update postgresql96 to new upstream version 9.6.8
Tested with:
fink -m rebuild postgresql96

Update postgresql96 to 9.6.8

---

10.9-libcxx/stable/main/finkinfo/database/postgresql94.info
10.9-libcxx/stable/main/finkinfo/database/postgresql95.info

update postgresql95 to version 9.5.12
update postgresql94 to version 9.4.17
changes are tested with fink -m

update  postgresql94 9.4.17 and  postgresql95 9.5.12

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/simplejson-py.info
10.9-libcxx/stable/main/finkinfo/sci/convertall.info

Update simplejson-py to latest upstream version.  Builds on macOS 10.13 with fink -m.

Simplejson py update

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/alabaster-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/flake8-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/mccabe-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pep8-naming-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pycodestyle-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pyflakes-py.info

@danielj7 these are needed for an update to another package. All tested with py27 and py36.

Pyflakes and associated pymod updates

---

10.9-libcxx/stable/main/finkinfo/graphics/pixman.info
10.9-libcxx/stable/main/finkinfo/graphics/pixman.patch

fixes this failure on 10.13/xcode9.3
http://lists.llvm.org/pipermail/cfe-dev/2017-August/055140.html

pixman: xcode9.3 fix

---

10.9-libcxx/stable/main/finkinfo/libs/wxcocoa293-shlibs.info
10.9-libcxx/stable/main/finkinfo/libs/wxwidgets300-cocoa.info
10.9-libcxx/stable/main/finkinfo/libs/wxwidgets300-cocoa.patch
10.9-libcxx/stable/main/finkinfo/sci/grass70.info

Continuation of #142. Apparently you can't push new commits to a PR that's been merged and I have to open a new PR.
Tries to fix some things in wxwidgets300-cocoa but eventually dist restricts it. Also dist restrict wxcocoa293 which is an -shlibs stub anyway.

dist restrict some wxWidget libraries

---

10.9-libcxx/stable/main/finkinfo/libs/perlmods/async-interrupt-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/berkeleydb-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/compress-raw-lzma-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/curses-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/data-messagepack-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/data-uuid-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/db-file-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/dbm-deep-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/devel-globaldestruction-xs-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/encode-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/git-wrapper-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/import-into-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/parallel-forkmanager-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/perlio-gzip-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/role-tiny-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/unicode-utf8-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/www-curl-pm.info
10.9-libcxx/stable/main/finkinfo/libs/perlmods/www-curl-pm.patch
10.9-libcxx/stable/main/finkinfo/libs/perlmods/xsloader-pm.info

Bunch of version updates to perlmods. I believe these all belong to @danielj7 . Tested on 10.11.

Perlmod updates

---

10.9-libcxx/stable/main/finkinfo/utils/dosbox.info
10.9-libcxx/stable/main/finkinfo/utils/dosbox.patch

...and also resolve a few compiler warnings. Former .patch was unused.

dosbox: fix FTBFS by using freebsd patch

---

10.9-libcxx/stable/main/finkinfo/utils/rkhunter.info

Update rkhunter to version 1.4.6

New upstream version of rkhunter

---

10.9-libcxx/stable/main/finkinfo/sci/triangle.info

Fixes build failure reported in bindist: http://bindist.finkproject.org/10.13/logs/triangle_1.6-2_41f48acb1a61b6288d0e6815ec7c291f.log

Portalble X11 paths and associated deps

---

10.9-libcxx/stable/main/finkinfo/devel/cmake.info

Tested with 'fink -m' on 10.13 against Xcode 9.3.

update cmake to 3.11.0 release

---

10.9-libcxx/stable/main/finkinfo/utils/unrar.info

Unrar: update to new upstream version (5.6.4)

---

10.9-libcxx/stable/main/finkinfo/devel/lazarus-doc.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-carbon.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-cocoa-32bit.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-cocoa.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-gtk2.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-qt4.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-qt5.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-win32.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-win64.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-wince-arm.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-wince-i386.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus.info
10.9-libcxx/stable/main/finkinfo/devel/qt5pas.info

2nd try. First was completely bogus.

Lazarus: update to new upstream version (1.8.4)

---

10.9-libcxx/stable/main/finkinfo/crypto/monero.info
10.9-libcxx/stable/main/finkinfo/crypto/monero.patch

Switch to newer boost
Switch to external libunbound & libminiupnpc
Switch to openssl110

monero: dep upgrades

---

10.9-libcxx/stable/main/finkinfo/utils/clamav.info

clamav: upstream patch release

---

10.9-libcxx/stable/main/finkinfo/net/rsync.info
10.9-libcxx/stable/main/finkinfo/net/rsync.patch

Update package to latest upstream patch release.

rsync 3.1.3

---

10.4/stable/main/finkinfo/10.4-EOL/devel/yasm.info
10.4/stable/main/finkinfo/10.4-EOL/utils/smartmontools.info
10.4/stable/main/finkinfo/10.5-EOL/devel/yasm.info
10.4/stable/main/finkinfo/10.5-EOL/utils/smartmontools.info
10.4/stable/main/finkinfo/devel/yasm.info
10.4/stable/main/finkinfo/utils/smartmontools.info
10.7/stable/main/finkinfo/devel/yasm.info
10.7/stable/main/finkinfo/utils/smartmontools.info
10.9-libcxx/stable/main/finkinfo/devel/yasm.info
10.9-libcxx/stable/main/finkinfo/utils/smartmontools.info

Unfortunately I am no longer actively using Fink, so I am no longer able to test these packages or provide updates. I would like to document this situation publicly so that someone else will hopefully see the opening and take over. I am of course always available for questions.

give up maintainership of packages

---

10.9-libcxx/stable/main/finkinfo/libs/lz4.info

lz4: update to new upstream version (1.8.2)

---

10.9-libcxx/stable/main/finkinfo/graphics/pil-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/olefile-py.info

both:
- update to recent upstream
- add py37 variant
- add license files and PKG-INFO to DocFiles
olefile-py: add InfoTest
pil-py:
- update source server
- use tab indentation everywhere

olefile-py&pil-py: update and add py37

---

10.9-libcxx/stable/main/finkinfo/sci/matplotlib-basemap-py.info
10.9-libcxx/stable/main/finkinfo/sci/mayavi2-py.info
10.9-libcxx/stable/main/finkinfo/sci/numexpr-py.info
10.9-libcxx/stable/main/finkinfo/sci/numpy-py.info
10.9-libcxx/stable/main/finkinfo/sci/numpy-py.patch

Fixes the problem with the environment SHELL from fink-bld (/usr/bin/false) not being a real shell.

fix numpy.distutils and SHELL issue (#121)

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/ptyprocess-py.info

ptyprocess-py: Update to newer upstream version (0.6.0), add py37 variant and add docfiles

ptyprocess-py: Update, add py37, add docfiles

---

10.9-libcxx/stable/main/finkinfo/utils/ansible-py.info

ansible 2.6.3

---

10.9-libcxx/stable/main/finkinfo/languages/libyaml.info
10.9-libcxx/stable/main/finkinfo/languages/libyaml.patch
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/yaml-py.info

yaml-py: update to 3.13 and adding py37 variant
libyaml: update to 0.2.1

libyaml &yaml-py: update to newer upstream version

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/cycler-py.info

cycler-py: add py37 variant

---

10.9-libcxx/stable/main/finkinfo/sci/nco.info

Simple upstream update from version 4.7.6 to 4.7.7

nco-4.7.7-1

---

10.9-libcxx/stable/main/finkinfo/utils/skhd.info

This is handy on its own but I've packaged it to support keyboard control of chunkwm, coming shortly.

New package skhd

---

10.9-libcxx/stable/main/finkinfo/utils/chunkwm.info

The closest you can get to i3 on a mac, it seems.

New package chunkwm 0.4.6

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/wxpython400-py.info

updated wx library and python wrapper.

wxpython400-py: new package.

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/wxutils-py.info

Utilities and convenience stuff for wxPython400-py

wxutils-py: new package: Utilities for wxPython

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pytz-py.info

I adjusted the expected values for the tests for py37.

pytz-py37: tests fixed

---

10.9-libcxx/stable/main/finkinfo/text/texinfo.info

checked with -m --build-as-nobody rebuild. no problems.

texinfo: add 10.14

---

10.9-libcxx/stable/main/finkinfo/libs/librasqal3-shlibs.info

librasqal3: enable 10.14

---

10.9-libcxx/stable/main/finkinfo/libs/qt5-qtbase.info
10.9-libcxx/stable/main/finkinfo/libs/qt5-qtbase.patch

The additions in the patch file may not be required, but seemed to make sense.

fix compilation on 10.14

---

10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-ellipsis-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-evaluate-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-forcats-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-haven-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-hmisc-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-knitr-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-lme4-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-maptools-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-mgcv-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-r6-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-readxl-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-stringi-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-stringr-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-xfun-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-yaml-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-zip-r.info

Sync'ed to current versions on r-project.org and added `CustomMirror` configuration with archive path to address #367.

R module updates to latest upstream

---

10.9-libcxx/stable/main/finkinfo/libs/libblosc1-shlibs.info

Hi.
I am not really sure about the license, as there is a mix for different parts. My best guess is BSD, but OSI-approved might also be right. Any opinions?
This packages aims to be used in pytables.

c-blosc: New package. Compression library.

---

10.9-libcxx/stable/main/finkinfo/sci/cernlib2006.info

No changes to compilation, thus no %r update.

Upstream source URL has changed. 

---

10.9-libcxx/stable/main/finkinfo/sci/pythia8.2.info

Update pythia8.2 to latest upstream version.

Update pythia to latest upstream version

---

10.9-libcxx/stable/main/finkinfo/crypto/libsodium13.info
10.9-libcxx/stable/main/finkinfo/crypto/libsodium17.info
10.9-libcxx/stable/main/finkinfo/crypto/libsodium23.info

Use a custom mirror to search all sodium source locations.

---

10.9-libcxx/stable/main/finkinfo/net/cyrus-sasl2.3.info

New cyrus-sasl upstream version

---

10.9-libcxx/stable/main/finkinfo/database/postgresql11.info
10.9-libcxx/stable/main/finkinfo/database/postgresql11.patch

new package postgresql11 (11.3)  for latest postgresql major version 11.

New package postgresql11 11.3

---

10.9-libcxx/stable/main/finkinfo/sci/r-base35.info

New upstream version

---

10.9-libcxx/stable/main/finkinfo/devel/lazarus-doc.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-carbon.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-cocoa-32bit.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-cocoa.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-gtk2.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-qt4.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-qt5.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-win32.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-win64.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-wince-arm.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-wince-i386.info
10.9-libcxx/stable/main/finkinfo/devel/lazarus.info

update MD5-sum and replace http: by https:

lazarus: update to newer upstream version (2.0.4)

---

10.9-libcxx/stable/main/finkinfo/crypto/gnupg2.info
10.9-libcxx/stable/main/finkinfo/crypto/gnutls28.info
10.9-libcxx/stable/main/finkinfo/crypto/libassuan2.info
10.9-libcxx/stable/main/finkinfo/crypto/libgcrypt20.info
10.9-libcxx/stable/main/finkinfo/crypto/libgpg-error.info
10.9-libcxx/stable/main/finkinfo/crypto/libgpgme11-1.9-shlibs.info
10.9-libcxx/stable/main/finkinfo/crypto/libtasn1-6-dev.info
10.9-libcxx/stable/main/finkinfo/libs/npth.info
10.9-libcxx/stable/main/finkinfo/utils/pinentry.info

Updates to the gnupg crypto set of packages.

Nieder crypto update

---

10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-ellipsis-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-pillar-r-1.3.1.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-vctrs-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-zeallot-r.info

New packages vctrs and zeallot.

Add a new CRAN package vctrs

---

10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-fs-r.info

cran-rcpp-r is added to BuildDep.

Add missing BuildDep

---

10.9-libcxx/stable/main/finkinfo/games/sdl2.info

update to v2.0.10.
Also be explicit that this is not the x11 variant.

sdl2 v2.0.10

---

10.9-libcxx/stable/main/finkinfo/sci/r-base31.info
10.9-libcxx/stable/main/finkinfo/sci/r-base32.info
10.9-libcxx/stable/main/finkinfo/sci/r-base33.info
10.9-libcxx/stable/main/finkinfo/sci/r-base35.info
10.9-libcxx/stable/main/finkinfo/sci/r-base36.info
10.9-libcxx/stable/main/finkinfo/sci/r-base36.patch

R 3.6.1 has been added.  CRAN and Bioconductor packages will follow.

Add r-base36

---

10.9-libcxx/stable/main/finkinfo/devel/floppy.info
10.9-libcxx/stable/main/finkinfo/devel/flow.info
10.9-libcxx/stable/main/finkinfo/devel/ftidy.info
10.9-libcxx/stable/main/finkinfo/devel/snoopy.info
10.9-libcxx/stable/main/finkinfo/devel/to-f90.info
10.9-libcxx/stable/main/finkinfo/sci/freehelix.info
10.9-libcxx/stable/main/finkinfo/sci/ifeffit.info

Also some minor cleanups. Resolves my packages on gcc7 migration tracker #484.

Update gfortran programs to gcc9

---

10.9-libcxx/stable/main/finkinfo/sci/r-base35.info

I forgot to raise the revision number for r-base35 in the previous commit.

Add r-base35 revision number

---

10.9-libcxx/stable/main/finkinfo/devel/ddd.info
10.9-libcxx/stable/main/finkinfo/devel/openmpi.info
10.9-libcxx/stable/main/finkinfo/sci/cdo.info
10.9-libcxx/stable/main/finkinfo/sci/dcw-gmt.info
10.9-libcxx/stable/main/finkinfo/sci/eccodes.info
10.9-libcxx/stable/main/finkinfo/sci/fftw3.info
10.9-libcxx/stable/main/finkinfo/sci/gdl.info
10.9-libcxx/stable/main/finkinfo/sci/gmt.info
10.9-libcxx/stable/main/finkinfo/sci/gmt5.info
10.9-libcxx/stable/main/finkinfo/sci/gmt6.info
10.9-libcxx/stable/main/finkinfo/sci/grib-api-fortran.info
10.9-libcxx/stable/main/finkinfo/sci/grib-api.info
10.9-libcxx/stable/main/finkinfo/sci/lapack350.info
10.9-libcxx/stable/main/finkinfo/sci/lapack360.info
10.9-libcxx/stable/main/finkinfo/sci/lapack361.info
10.9-libcxx/stable/main/finkinfo/sci/lapack371.info
10.9-libcxx/stable/main/finkinfo/sci/lapack380.info
10.9-libcxx/stable/main/finkinfo/sci/nco.info
10.9-libcxx/stable/main/finkinfo/sci/ncview.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-c13.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-c15.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-cxx4.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-fortran7.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-fortran8.info
10.9-libcxx/stable/main/finkinfo/sci/pgplot.info
10.9-libcxx/stable/main/finkinfo/sci/wip.info
10.9-libcxx/stable/main/finkinfo/text/ghostscript.info
10.9-libcxx/stable/main/finkinfo/web/wget.info

With this I'm handing over all the packages that I have been maintaining.
It was great working with Fink for many years, but I feel I do not have sufficient time to keep my packages up to date.
I hope someone else will pick them up.
devel/ddd.info
devel/openmpi.info
sci/cdo.info
sci/dcw-gmt.info
sci/eccodes.info
sci/fftw3.info
sci/gdl.info
sci/gmt.info
sci/gmt5.info
sci/gmt6.info
sci/grib-api-fortran.info
sci/grib-api.info
sci/lapack350.info
sci/lapack360.info
sci/lapack361.info
sci/lapack371.info
sci/lapack380.info
sci/nco.info
sci/ncview.info
sci/netcdf-c13.info
sci/netcdf-c15.info
sci/netcdf-cxx4.info
sci/netcdf-fortran7.info
sci/netcdf-fortran8.info
sci/pgplot.info
sci/wip.info
text/ghostscript.info
web/wget.info

Handing over remkos' packages

---

10.9-libcxx/stable/main/finkinfo/database/postgresql12.info
10.9-libcxx/stable/main/finkinfo/database/postgresql12.patch

new package postgresql12 (12.1) for latest postgresql major version 12.

New package postgresql12 12.1

---

10.9-libcxx/stable/main/finkinfo/libs/cfitsio.info
10.9-libcxx/stable/main/finkinfo/sci/biggles-py.info
10.9-libcxx/stable/main/finkinfo/sci/gildas.info
10.9-libcxx/stable/main/finkinfo/sci/gsl.info
10.9-libcxx/stable/main/finkinfo/sci/slatec.info
10.9-libcxx/stable/main/finkinfo/sci/sundials.info
10.9-libcxx/stable/main/finkinfo/sci/wcstools.info

I am no longer a Fink user, so I am marking the package I used to maintain as unmaintained.

Drop maintainership of packages

---

10.9-libcxx/stable/main/finkinfo/text/texlive-10.15.info
10.9-libcxx/stable/main/finkinfo/text/texlive-texmf-10.15.info
10.9-libcxx/stable/main/finkinfo/text/texlive-texmf-luajittex.patch

luajittex segfaults on 10.15, so disable it there and prevent it from being run from texlive-texmf.
Fixes #490
@okayamat

disable luajittex in texlive on 10.15

---

10.9-libcxx/stable/main/finkinfo/games/sjeng-rollup-4c7ddc3.patch
10.9-libcxx/stable/main/finkinfo/games/sjeng.info

Permissions problem under --build-as-nobody (fink's default mode) led me down a rabbit-hole of fixing things.

sjeng: Fix FTBFS and import unreleased upstream revisions

---

10.9-libcxx/stable/main/finkinfo/net/libtorrent15-openssl1.1.patch
10.9-libcxx/stable/main/finkinfo/net/libtorrent15.info
10.9-libcxx/stable/main/finkinfo/net/libtorrent19.info
10.9-libcxx/stable/main/finkinfo/net/libtorrent20.info

* don't bother patching configure if regenerating it from .ac
* redoing autotools needs libtool2
* boost updates
* openssl update (issue #499)
* instrument the build to make sure we catch all deps

libtorrent* build cleanups

---

10.9-libcxx/stable/main/finkinfo/net/stone-openssl110.patch
10.9-libcxx/stable/main/finkinfo/net/stone.info

Thanks for the patch, debbugs!

stone: switch to openssl110

---

10.9-libcxx/stable/main/finkinfo/games/sdl2.info
10.9-libcxx/stable/main/finkinfo/games/sdl2.patch

Tested on 10.11 system, no response to maintainer contact.

Updated sdl2 with patch for 10.11 systems.

---

10.9-libcxx/stable/main/finkinfo/graphics/ffmpeg2theora.info
10.9-libcxx/stable/main/finkinfo/graphics/ffmpegthumbnailer.info
10.9-libcxx/stable/main/finkinfo/graphics/ffmpegthumbnailer.patch
10.9-libcxx/stable/main/finkinfo/graphics/opencv3.2-shlibs-ffmpeg4.patch
10.9-libcxx/stable/main/finkinfo/graphics/opencv3.2-shlibs.info
10.9-libcxx/stable/main/finkinfo/libs/libquicktime1.info
10.9-libcxx/stable/main/finkinfo/sound/moc.info
10.9-libcxx/stable/main/finkinfo/sound/moc.patch
10.9-libcxx/stable/main/finkinfo/sound/pianobar.info
10.9-libcxx/stable/main/finkinfo/utils/goldendict-mac-upstream.patch
10.9-libcxx/stable/main/finkinfo/utils/goldendict-mac.info
10.9-libcxx/stable/main/finkinfo/utils/goldendict-mac.patch
10.9-libcxx/stable/main/finkinfo/utils/goldendict-x11-upstream.patch
10.9-libcxx/stable/main/finkinfo/utils/goldendict-x11.info
10.9-libcxx/stable/main/finkinfo/utils/goldendict-x11.patch

This switches all ffmpeg3 users to ffmpeg4.

ffmpeg upgrades

---

10.9-libcxx/stable/main/finkinfo/graphics/opencv2.4-shlibs-ffmpeg4.patch
10.9-libcxx/stable/main/finkinfo/graphics/opencv2.4-shlibs.info
10.9-libcxx/stable/main/finkinfo/kde/ffmpegthumbs4.info
10.9-libcxx/stable/main/finkinfo/kde/ffmpegthumbs4.patch
10.9-libcxx/stable/main/finkinfo/kde/libkfilemetadata4-shlibs.info
10.9-libcxx/stable/main/finkinfo/kde/nepomuk-core.info
10.9-libcxx/stable/main/finkinfo/libs/octmods/video-oct.info
10.9-libcxx/stable/main/finkinfo/libs/octmods/video-oct.patch
10.9-libcxx/stable/main/finkinfo/sound/mpd-ffmpeg4.patch
10.9-libcxx/stable/main/finkinfo/sound/mpd.info

This switches all ffmpeg2 users to ffmpeg4.

Ffmpeg upgrades older

---

10.9-libcxx/stable/main/finkinfo/devel/libtool2.info

libtool2: upstream bug fix

---

10.9-libcxx/stable/main/finkinfo/text/libharfbuzz0-shlibs.info

Fix the format

---

10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-baseline-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-deriv-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-devtools-r-2.0.1.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-devtools-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-doby-r-4.6-2.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-doby-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-factominer-r-1.42.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-farver-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-fastmap-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-ggplot2-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-ggrepel-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-isoband-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-jpeg-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-latticeextra-r-0.6-28.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-latticeextra-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-limsolve-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-nmf-r-0.21.0.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-rversions-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-scales-r-1.0.0.info

Eight new packages.
deriv: doby
farver: scales
ggrepel: factominer
fastmap: shiny
isoband: ggplot2
jpeg: latticeextra
limsolve: baseline
rversions: devtools
Also, nmf and sensominer have a newer version.

CRAN New upstream versions that require new packages

---

10.9-libcxx/stable/main/finkinfo/net/mtr.info
10.9-libcxx/stable/main/finkinfo/net/mtr.patch

mtr: new upstream

---

10.9-libcxx/stable/main/finkinfo/utils/dateutils.info

This should be pretty straightforward.

dateutils: new upstream

---

10.9-libcxx/stable/main/finkinfo/graphics/aquaterm.info

Added check that XCode.app has been run by checking for presence of /Library/Developer/PrivateFrameworks

Check aquaterm build environment has run XCode.app.

---

10.9-libcxx/stable/main/finkinfo/net/tnftp.info

Also added dependencies I missed before. Can someone check htis for me?

tnftp: new upstream

---

10.9-libcxx/stable/main/finkinfo/sci/relax.info

Not compatible with gmt > v4
Part of #481
@sbarbot

relax: bump all possible dependencies.

---

10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-slam-r.info

Cran slam r

---

10.9-libcxx/stable/main/finkinfo/net/rsync.info
10.9-libcxx/stable/main/finkinfo/net/rsync.patch

rsync autoconf: work-around for new xcode

---

10.9-libcxx/stable/main/finkinfo/libs/perlmods/cpan-pm.info

Trivial version update. But could someone check whether the self-tests perform network access, and disable as appropriate?

cpan-pmXXX new version

---

10.9-libcxx/stable/main/finkinfo/net/telnet.info

Just added Big Sur so I can get telnet.

telnet: add Big Sur

---

10.9-libcxx/stable/main/finkinfo/graphics/libtiff5-shlibs.info
10.9-libcxx/stable/main/finkinfo/graphics/libtiff5-shlibs.patch
10.9-libcxx/stable/main/finkinfo/libs/libdeflate0-shlibs.info
10.9-libcxx/stable/main/finkinfo/libs/libdeflate0-shlibs.patch
10.9-libcxx/stable/main/finkinfo/libs/libzstd1-shlibs.info

Enabled zstd and deflate support.

Libtiff update

---

10.9-libcxx/stable/main/finkinfo/utils/qemu.info

gnutls is updated from 28 to 30. brief test with one image worked.

qemu: update gnutls dependence

---

10.9-libcxx/stable/main/finkinfo/net/nut-flag-ordering.patch
10.9-libcxx/stable/main/finkinfo/net/nut-openssl110.patch
10.9-libcxx/stable/main/finkinfo/net/nut.info
10.9-libcxx/stable/main/finkinfo/net/nut.patch

openssl upgrade (for issue #499), and general dependency and build-system audit/fixes

Nut update

---

10.9-libcxx/stable/main/finkinfo/graphics/dcraw.info

No code change, no need to recompile, no revision bump.

dcraw: update of homepage and source

---

10.9-libcxx/stable/main/finkinfo/utils/unrar.info

unrar: update to upstream version 6.0.4

---

10.9-libcxx/stable/main/finkinfo/sci/checkmol.info
10.9-libcxx/stable/main/finkinfo/sci/mol2ps.info

checkmol: update of homepage only.

checkmol & mol2ps: update to upstream version

---

10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-chemospec-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-effects-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-memoise-r-1.1.0.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-memoise-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-partitions-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-rappdirs-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-readr-r-1.3.1.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-tidyr-r-1.1.0.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-vgamdata-r-1.0-3.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-vgamdata-r.info

Cran 20210404

---

10.9-libcxx/stable/main/finkinfo/text/latex2html-issue67.patch
10.9-libcxx/stable/main/finkinfo/text/latex2html.info

Fix for "[Fink-users] Latex2html too old version ?"

latex2html: new version

---

10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-mathjaxr-r.info
10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-mstate-r.info

Fix for cran modules missing dependencies #793

Fixed a wrongly names dep; mathjaxr is a new package

---

10.9-libcxx/stable/main/finkinfo/database/postgresql10.info
10.9-libcxx/stable/main/finkinfo/database/postgresql10.patch
10.9-libcxx/stable/main/finkinfo/database/postgresql11.info
10.9-libcxx/stable/main/finkinfo/database/postgresql11.patch
10.9-libcxx/stable/main/finkinfo/database/postgresql12.info
10.9-libcxx/stable/main/finkinfo/database/postgresql12.patch
10.9-libcxx/stable/main/finkinfo/database/postgresql94.info
10.9-libcxx/stable/main/finkinfo/database/postgresql95.info
10.9-libcxx/stable/main/finkinfo/database/postgresql96.info
10.9-libcxx/stable/main/finkinfo/database/postgresql96.patch

- update to latest upstream version
- changed readline dependency to readline8
- moved pkgconfig files to dev split off
- added next postgresql major version 13 in replaced by and conflict section (dev splittoff)
- removed dependency to fink-mirrors (>= 0.28.7.1-2)

postgresql updates

---

10.9-libcxx/stable/main/finkinfo/sci/grass64.info
10.9-libcxx/stable/main/finkinfo/sci/grass64.patch
10.9-libcxx/stable/main/finkinfo/sci/grass72.info
10.9-libcxx/stable/main/finkinfo/sci/grass72.patch

Fixes some FTBFS/library-inconsistencies, and updates some dependency versions.

Grass dep fixes

---

10.9-libcxx/stable/main/finkinfo/base/expat1.info

Remove dependency on xz (closing #837)

Revert expat1 to bzip2 source

---

10.9-libcxx/stable/main/finkinfo/sci/xrootd4.info
10.9-libcxx/stable/main/finkinfo/sci/xrootd4.patch

This is likely the last xrootd v4 release upstream.

xrootd4: new version

---

10.9-libcxx/stable/main/finkinfo/net/tcpflow.info
10.9-libcxx/stable/main/finkinfo/net/tcpflow.patch

Tcpflow update

---

10.9-libcxx/stable/main/finkinfo/graphics/povray.info
10.9-libcxx/stable/main/finkinfo/graphics/povray.patch

Not sure the git handle for maintainer Andrew Rohl

povray: new version, dep upgrades

---

10.9-libcxx/stable/main/finkinfo/devel/libtool2.info

Thanks Nieder for noticing the problem and finding a quick-fix!

Fix regexps for Big Sur darwin-version

---

10.9-libcxx/stable/main/finkinfo/languages/gcc10.info
10.9-libcxx/stable/main/finkinfo/languages/gcc11-apfs.patch
10.9-libcxx/stable/main/finkinfo/languages/gcc11-build-sysroot.patch
10.9-libcxx/stable/main/finkinfo/languages/gcc11-macos12.patch
10.9-libcxx/stable/main/finkinfo/languages/gcc11.info
10.9-libcxx/stable/main/finkinfo/languages/gcc11.patch
10.9-libcxx/stable/main/finkinfo/languages/gcc5-10.14.5.info
10.9-libcxx/stable/main/finkinfo/languages/gcc5-10.14.info
10.9-libcxx/stable/main/finkinfo/languages/gcc5.info
10.9-libcxx/stable/main/finkinfo/languages/gcc6-10.14.5.info
10.9-libcxx/stable/main/finkinfo/languages/gcc6-10.14.info
10.9-libcxx/stable/main/finkinfo/languages/gcc6.info
10.9-libcxx/stable/main/finkinfo/languages/gcc7-10.14.5.info
10.9-libcxx/stable/main/finkinfo/languages/gcc7-10.14.info
10.9-libcxx/stable/main/finkinfo/languages/gcc7.info
10.9-libcxx/stable/main/finkinfo/languages/gcc8-10.14.5.info
10.9-libcxx/stable/main/finkinfo/languages/gcc8-10.14.info
10.9-libcxx/stable/main/finkinfo/languages/gcc8.info
10.9-libcxx/stable/main/finkinfo/languages/gcc9.info

New package for gcc11 upstream.

new gcc11 package

---

10.9-libcxx/stable/main/finkinfo/editors/autogen.info

updates autogen to v 5.18.16
Some fixes for upstream bugs

Autogen update

---

10.9-libcxx/stable/main/finkinfo/devel/ply-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/asteval-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/filelock-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/lmfit-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pipdeptree-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/psutil-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pv-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pypubsub3-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pypubsub4-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/sphinxcontrib-websupport-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/webob-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/whoosh-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/wxpython400-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/wxutils-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/xapian22-py.info
10.9-libcxx/stable/main/finkinfo/libs/pythonmods/xapian30-py.info
10.9-libcxx/stable/main/finkinfo/sci/peakutils-py.info
10.9-libcxx/stable/main/finkinfo/sci/scikit-learn-py.info
10.9-libcxx/stable/main/finkinfo/sci/wxmplot-py.info

I am not really working with these packages any more. They were part of a project, I abandoned a while ago.

Unmaintain python stuff

---

10.9-libcxx/stable/main/finkinfo/sci/netcdf-c11-shlibs.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-c13-shlibs.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-c15-h5_tst.patch
10.9-libcxx/stable/main/finkinfo/sci/netcdf-c15.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-c18.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-c7.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-cxx4.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-fortran7.info
10.9-libcxx/stable/main/finkinfo/sci/netcdf-fortran8.info

Update netcdf packages to use hdf5.200 (v1.12.0) and gcc11 as possible.
This will help with #887 and #874

Netcdf updates

---

10.9-libcxx/stable/main/finkinfo/graphics/vigra5.info
10.9-libcxx/stable/main/finkinfo/graphics/vigra5.patch

NB: Fixing a bug in hdf test that was previously causing non-detection of
it altgether, at least on current cmake.

vigra: Bump deps

---

10.9-libcxx/stable/main/finkinfo/kde/libkf5sonnetcore5-shlibs.info
10.9-libcxx/stable/main/finkinfo/kde/lokalize4.info
10.9-libcxx/stable/main/finkinfo/text/libhunspell1.6-shlibs.info
10.9-libcxx/stable/main/finkinfo/text/libhunspell1.7-shlibs.info

This is a new libversion, and upgrades of some packages that were using older versions, all listing @nieder as maintainer. Will work on the other unmaintained ones later, didn't want to step on an active one's toes.

New libhunspell

---

10.9-libcxx/stable/main/finkinfo/editors/vim.info
10.9-libcxx/stable/main/finkinfo/sci/bowtie2.info
10.9-libcxx/stable/main/finkinfo/sci/bowtie2.patch
10.9-libcxx/stable/main/finkinfo/utils/fdupes.info

Adding new package for fdupes.

Htodd fdupes

---

10.9-libcxx/stable/main/finkinfo/sci/libjags4-shlibs.info

A new package. I am testing this new package with R through rjags package and so far it seems working.

Library for Just Another Gibbs Sampler

---

10.9-libcxx/stable/main/finkinfo/utils/gawk.info
10.9-libcxx/stable/main/finkinfo/utils/gawk.patch

Allow native build for gawk on arm64

---

10.9-libcxx/stable/main/finkinfo/graphics/libvpx16-shlibs.info
10.9-libcxx/stable/main/finkinfo/graphics/libvpx8-shlibs.info

Update libvpx to latest upstream tag v1.13.0
This knows about macOS through Ventura and also knows Apple silicon.

Libvpx update to v1.13.0

---

10.9-libcxx/stable/main/finkinfo/web/lighttpd.info

lighttpd: update to lighttpd 1.4.72

lighttpd: update to lighttpd 1.4.72

---

10.9-libcxx/stable/main/finkinfo/web/lighttpd.info

lighttpd: update to lighttpd 1.4.73

lighttpd: update to lighttpd 1.4.73

---

10.9-libcxx/stable/main/finkinfo/libs/pythonmods/snowballstemmer-py.info

new version required for newer sphinx-py
tested py27/35/38/310 on 10.14.6

snowballstemmer-py: v2.2.0

---

10.9-libcxx/stable/main/finkinfo/web/lighttpd.info

lighttpd: update to lighttpd 1.4.76
replaces #1130

lighttpd: update to lighttpd 1.4.76

---

10.9-libcxx/stable/main/finkinfo/net/libcurl4.info

Continuating work from "[Fink-users] Update to cURL?"

Libcurl upgrades

---

10.9-libcxx/stable/main/finkinfo/libs/perlmods/scalar-list-utils-pm.info

scalar-list-utils-pm updated for perl 5.34.1

---

10.9-libcxx/stable/main/finkinfo/crypto/gsasl19-shlibs.info

Updated call to autoreconf to no replace updated/missing files.  See issue #1177

update to gsasl for Xcode 16. 

---

10.9-libcxx/stable/main/finkinfo/shells/bash.info
10.9-libcxx/stable/main/finkinfo/shells/bash.patch

Update to latest upstream 5.2.37
Closes maybe #1176

bash: 5.2.37

---

10.9-libcxx/stable/main/finkinfo/graphics/aquaterm.info

Simple addition of 15.0 to distribution field

aquaterm update for Sequoia

---

10.9-libcxx/stable/main/finkinfo/web/lighttpd.info

lighttpd: update to lighttpd 1.4.79

lighttpd: update to lighttpd 1.4.79

---

10.9-libcxx/stable/main/finkinfo/text/docbook-utils.info

Update link to source file since old link is non-existent and finkmaster non-functional

docbook-utils update source file source

---

10.9-libcxx/stable/main/finkinfo/web/lighttpd.info

lighttpd: update to lighttpd 1.4.82

lighttpd: update to lighttpd 1.4.82
